import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { View } from 'react-native';
import { socialEvents } from '@/api/social-events-v10';
import { Screen, Card, Txt, Button, Field, Loading } from '@/components/ui';
import { showError } from '@/lib/errors';
import { confirmAction } from '@/components/community/platform';
export default function Connections(){
  const q=useQuery({queryKey:['friendships'],queryFn:socialEvents.friends}),invites=useQuery({queryKey:['groupInvitations'],queryFn:socialEvents.invitations});
  const [handle,setHandle]=useState(''),[busy,setBusy]=useState(false);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await Promise.all([q.refetch(),invites.refetch()]);}catch(e){showError(e);}finally{setBusy(false);}};
  return <Screen refreshing={q.isRefetching||invites.isRefetching} onRefresh={()=>{void q.refetch();void invites.refetch();}}><Txt variant="title">Your connections</Txt><Txt tone="muted">Friendships start with a request. You join a group after accepting its invitation.</Txt><Card><Field label="Member username" value={handle} onChangeText={setHandle} placeholder="@username" maxLength={31} autoCapitalize="none"/><Button label="Send friend request" busy={busy} onPress={()=>void act(async()=>{await socialEvents.requestFriend(handle);setHandle('');})}/></Card>{q.isPending||invites.isPending?<Loading/>:null}{q.error||invites.error?<Txt tone="danger">{q.error?.message||invites.error?.message}</Txt>:null}<Card><Txt variant="heading">Friend requests</Txt>{q.data?.incoming.length?q.data.incoming.map(p=><View key={p.id} style={{gap:8}}><Txt>{p.name} · @{p.handle}</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><Button small label="Accept" busy={busy} onPress={()=>void act(()=>socialEvents.answerFriend(p.id,'accept'))}/><Button small label="Decline" variant="secondary" busy={busy} onPress={()=>void act(()=>socialEvents.answerFriend(p.id,'decline'))}/></View></View>):<Txt tone="muted">No pending requests.</Txt>}{q.data?.outgoing.map(p=><View key={p.id} style={{gap:8}}><Txt>Waiting for {p.name}</Txt><Button small label="Cancel request" variant="secondary" busy={busy} onPress={()=>void act(()=>socialEvents.answerFriend(p.id,'cancel'))}/></View>)}</Card><Card><Txt variant="heading">Group invitations</Txt>{invites.data?.length?invites.data.map(i=><View key={i.id} style={{gap:8}}><Txt>{i.name}</Txt><Txt variant="small" tone="muted">Invited by {i.inviter} · expires {new Date(i.expiresAt).toLocaleDateString()}</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><Button small label="Accept invitation" busy={busy} onPress={()=>void act(async()=>{const result=await socialEvents.answerGroup(i.id,true);if(result.roomId)router.push(`/chat/${result.roomId}`);})}/><Button small label="Decline" variant="secondary" busy={busy} onPress={()=>void act(()=>socialEvents.answerGroup(i.id,false))}/></View></View>):<Txt tone="muted">No group invitations.</Txt>}</Card><Card><Txt variant="heading">Friends</Txt>{q.data?.friends.length?q.data.friends.map(p=><View key={p.id} style={{gap:8}}><Button small variant="ghost" label={`${p.name} · @${p.handle}`} onPress={()=>router.push(`/profile/${p.handle}`)}/><Button small label="Remove friend" variant="secondary" busy={busy} onPress={()=>confirmAction(`Remove ${p.name}?`,'This ends your friendship.',()=>void act(()=>socialEvents.answerFriend(p.id,'remove')))}/></View>):<Txt tone="muted">Accepted friendships appear here.</Txt>}</Card></Screen>;
}
