import { useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState, type ReactNode } from 'react';
import { Switch, View } from 'react-native';
import { identityApi, type IdentityPreferences } from '@/lib/identity-v9';
import { api } from '@/api/endpoints';
import { BirthdayFields, EMPTY_BIRTHDAY, judgeBirthday } from '@/components/BirthdayFields';
import { Button, ErrorState, Field, Loading, Screen, Txt } from '@/components/ui';
import { notify } from '@/components/community/platform';
import { errorMessage } from '@/lib/errors';
import { useT } from '@/lib/i18n';
import { radius, useTheme } from '@/theme';
import { ContactImporter } from '@/components/ContactImporter';

export default function PrivacyDashboard() {
  const t = useT();
  const query=useQuery({queryKey:['identityDashboard'],queryFn:identityApi.dashboard});const client=useQueryClient();
  const [handle,setHandle]=useState<string|null>(null);const [links,setLinks]=useState<string|null>(null);const [person,setPerson]=useState('');const [kind,setKind]=useState('favorite');
  const [birthday,setBirthday]=useState(EMPTY_BIRTHDAY);const [contacts,setContacts]=useState('');const [matches,setMatches]=useState<{handle:string;name:string}[]>([]);
  const save=async(patch:Partial<IdentityPreferences>)=>{try{await identityApi.preferences(patch);await client.invalidateQueries();}catch(e){notify('Could not save',errorMessage(e));}};
  const change=async(target:string,relationship:string,on:boolean)=>{try{await identityApi.person(target,relationship,on);await query.refetch();setPerson('');}catch(e){notify('Could not update',errorMessage(e));}};
  if(query.isPending)return <Loading/>;if(query.isError||!query.data)return <ErrorState error={query.error} onRetry={()=>void query.refetch()}/>;
  const d=query.data,p=d.preferences;
  const handleValue=handle??p.handle,linksValue=links??p.socialLinks.map(link=>`${link.label}|${link.url}`).join('\n');
  return <Screen><Txt variant="title">Privacy dashboard</Txt><Txt tone="muted">Your identity, safety and people.</Txt><Button label="Account security and devices" variant="secondary" onPress={()=>router.push('/security' as never)}/>
    <Card title="Your identity"><Field label="Username" value={handleValue} onChangeText={setHandle} maxLength={30} autoCapitalize="none"/><Button label="Save username" onPress={()=>void save({handle:handleValue})}/><Txt>{t('privacy.language.title')}</Txt><Choices values={['en','fr','es','de','pt','ja','ko','zh','hi','ar']} value={p.language} onSelect={language=>void save({language})}/><Field label="Profile links" value={linksValue} onChangeText={setLinks} multiline placeholder="Portfolio|https://example.com" hint="Up to six links, one per line: label|https://address"/><Button label="Save links" onPress={()=>void save({socialLinks:linksValue.split('\n').filter(Boolean).map(line=>{const [label,...url]=line.split('|');return {label:label?.trim()??'',url:url.join('|').trim()};})})}/><Txt>Profile accent</Txt><Choices values={['0','25','140','175','210','250','290','330']} value={String(p.profileHue)} onSelect={hue=>void save({profileHue:Number(hue)})}/></Card>
    <Card title="Who can reach you"><Txt>Who can mention you</Txt><Choices values={['everyone','following','none']} value={p.mentionPrivacy} onSelect={mentionPrivacy=>void save({mentionPrivacy})}/><Txt>Who can invite you</Txt><Choices values={['everyone','following','none']} value={p.invitePrivacy} onSelect={invitePrivacy=>void save({invitePrivacy})}/><Toggle label="Appear in people search" value={p.searchVisible} onChange={searchVisible=>void save({searchVisible})}/><Toggle label="Hide followers list" value={p.hideFollowers} onChange={hideFollowers=>void save({hideFollowers})}/><Toggle label="Hide following list" value={p.hideFollowing} onChange={hideFollowing=>void save({hideFollowing})}/><Toggle label="Restricted mode: only 13+ communities" value={p.restrictedMode} onChange={restrictedMode=>void save({restrictedMode})}/><Txt>Sensitive content</Txt><Choices values={d.ageBand==='18+'?['blur','hide','show']:['blur','hide']} value={p.sensitiveContent} onSelect={sensitiveContent=>void save({sensitiveContent})}/><Toggle label="High contrast" value={p.highContrast} onChange={highContrast=>void save({highContrast})}/><Txt>Text size</Txt><Choices values={['standard','large','largest']} value={p.textScale} onSelect={textScale=>void save({textScale})}/></Card>
    <Card title="Age and teen safety"><Txt>{d.ageChecked?`Checked eligibility: ${d.ageBand}`:'Confirm your birthday once to establish age eligibility.'}</Txt><Txt tone="muted">Teens can message mutual follows only, with daily limits. Settings cannot unlock age-gated communities.</Txt>{!d.ageChecked&&<><BirthdayFields value={birthday} onChange={setBirthday}/><Button label="Confirm eligibility" onPress={async()=>{const verdict=judgeBirthday(birthday);if(verdict.kind!=='ok')return notify('Check birthday','Enter a valid birthday, age 13 or older.');try{await api.confirmAge({year:verdict.year,month:verdict.month,day:verdict.day});await query.refetch();}catch(e){notify('Could not confirm',errorMessage(e));}}}/></>}</Card>
    <Card title="Your people"><Field label="Member username" value={person} onChangeText={setPerson} autoCapitalize="none" placeholder="@username"/><Choices values={['favorite','close_friend','restrict','mute']} value={kind} onSelect={setKind}/><Button label="Add member" onPress={()=>void change(person,kind,true)}/>{d.people.length+d.muted.length===0&&<Txt tone="muted">Your lists are empty.</Txt>}{[...d.people,...d.muted.map(p=>({...p,kind:'mute'}))].map(p=><View key={`${p.kind}:${p.userId}`} style={{gap:4}}><Txt onPress={()=>router.push(`/profile/${p.handle}` as never)}>{p.name} · @{p.handle}</Txt><Txt variant="caption" tone="muted">{p.kind?.replace('_',' ')}</Txt><Button label="Remove" small variant="secondary" onPress={()=>void change(p.handle,p.kind!,false)}/></View>)}</Card>
    <Card title="Find people you know"><ContactImporter onMatches={setMatches}/><Txt tone="muted">Or paste email addresses you have permission to use. They are matched transiently and never retained.</Txt><Field label="Contact emails" value={contacts} onChangeText={setContacts} multiline autoCapitalize="none"/><Button label="Find contacts" onPress={async()=>{try{setMatches(await identityApi.contacts(contacts.split(/[\s,;]+/).filter(Boolean)));setContacts('');}catch(e){notify('Could not find contacts',errorMessage(e));}}}/>{matches.map(p=><Button key={p.handle} label={`${p.name} · @${p.handle}`} variant="secondary" onPress={()=>router.push(`/profile/${p.handle}` as never)}/>)}</Card>
  </Screen>;
}
function Card({title,children}:{title:string;children:ReactNode}){const theme=useTheme();return <View style={{gap:14,padding:16,borderRadius:radius.card,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border}}><Txt variant="heading">{title}</Txt>{children}</View>;}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={{flexDirection:'row',alignItems:'center',gap:12}}><Txt style={{flex:1}}>{label}</Txt><Switch accessibilityLabel={label} value={value} onValueChange={onChange}/></View>;}
function Choices({values,value,onSelect}:{values:string[];value:string;onSelect:(v:string)=>void}){return <View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{values.map(v=><Button key={v} label={v.replace('_',' ')} small variant={v===value?'primary':'secondary'} onPress={()=>onSelect(v)}/>)}</View>;}
