import {useQuery} from '@tanstack/react-query';
import {router} from 'expo-router';
import {useState} from 'react';
import {View} from 'react-native';
import {smartSearch,type SearchKind,type SearchResult} from '@/api/search-v10';
import {Screen,Card,Txt,Field,Button,Chip,Loading} from '@/components/ui';
import {showError} from '@/lib/errors';
import {appHrefFromServerHref} from '@/lib/hrefs';
function Results({rows}:{rows:SearchResult[]}){return <>{rows.map(r=><Card key={`${r.kind}:${r.id}`}><Txt variant="caption" tone="muted">{r.kind}</Txt><Txt variant="heading">{r.title}</Txt><Txt tone="muted">{r.excerpt}</Txt><Button variant="secondary" label="Open" onPress={()=>router.push(appHrefFromServerHref(r.href) as never)}/></Card>)}</>;}
export default function SmartSearch(){
 const status=useQuery({queryKey:['semanticStatus'],queryFn:smartSearch.status}),recs=useQuery({queryKey:['semanticRecommendations'],queryFn:smartSearch.recommendations});
 const [query,setQuery]=useState(''),[kind,setKind]=useState<SearchKind|'all'>('all'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[results,setResults]=useState<SearchResult[]|null>(null);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await Promise.all([status.refetch(),recs.refetch()]);}catch(e){showError(e);}finally{setBusy(false);}};
 return <Screen><Txt variant="title">Find your people</Txt><Txt tone="muted">Describe an interest or the kind of community you want. Smart search compares meaning.</Txt>{status.isPending?<Loading/>:null}{status.error?<Txt tone="danger">{status.error.message}</Txt>:null}{status.data&&!status.data.configured?<Card><Txt variant="heading">Awaiting smart search setup</Txt><Txt tone="muted">The app owner needs to connect an embedding provider. Regular search remains available.</Txt><Button label="Open Explore" onPress={()=>router.push('/(tabs)/explore' as never)}/></Card>:null}<Card><Field label="What are you looking for?" value={query} onChangeText={setQuery} maxLength={800} multiline placeholder="People who enjoy manga and drawing"/><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{(['all','post','community','person'] as const).map(k=><Chip key={k} label={k} selected={kind===k} onPress={()=>setKind(k)}/>)}</View><Txt variant="small" tone="muted">Agree to send search text, and your chosen interests when enabling recommendations, to the configured AI provider.</Txt><Chip label={consent?'AI provider consent: on':'Agree to AI provider processing'} selected={consent} onPress={()=>setConsent(!consent)}/><Button label="Search by meaning" busy={busy} disabled={!status.data?.configured||!consent||query.trim().length<2} onPress={()=>void act(async()=>setResults((await smartSearch.search(query,kind,consent)).results))}/></Card>{results?<><Txt variant="heading">Search results</Txt>{!results.length?<Txt tone="muted">No accessible indexed matches yet. Try another phrase or regular search.</Txt>:<Results rows={results}/>}</>:null}<Card><Txt variant="heading">Recommendations from your interests</Txt><Txt tone="muted">Match the interests in your profile. Turning this off removes your saved interest vector.</Txt><Button label={status.data?.personalized?'Turn off recommendations':'Enable recommendations'} busy={busy} disabled={!status.data?.personalized&&(!consent||!status.data?.configured)} onPress={()=>void act(()=>smartSearch.personalize(!status.data?.personalized,consent))}/></Card>{recs.error?<Txt tone="danger">{recs.error.message}</Txt>:null}{recs.data?.enabled?<Results rows={recs.data.results}/>:null}</Screen>;
}
