import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { View } from "react-native";
import { Button, Card, Chip, Field, Txt, Loading } from "@/components/ui";
import { ContentMedia } from "./ContentMedia";
import { mediaV10 } from "@/api/media-v10";
import type { MediaInput } from "@/api/content-types";
import { pickContentFile } from "@/lib/content-media";
import { showError } from "@/lib/errors";
import { confirmAction, notify } from "@/components/community/platform";
export function MediaLibraryPicker({kind,onSelect,manage=false,collapsed=false}:{kind:"gif"|"audio";onSelect?:(media:MediaInput)=>void;manage?:boolean;collapsed?:boolean}){
  const client=useQueryClient(),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[title,setTitle]=useState(""),[artist,setArtist]=useState(""),[tags,setTags]=useState(""),[rights,setRights]=useState(false),[file,setFile]=useState<MediaInput|null>(null),[busy,setBusy]=useState(false),[license,setLicense]=useState("");
  const [open,setOpen]=useState(!collapsed);
  const [previewId,setPreviewId]=useState<number|null>(null);
  const q=useQuery({queryKey:["mediaLibrary",kind,search],queryFn:()=>mediaV10.search(kind,search),enabled:open});
  async function run(fn:()=>Promise<unknown>){setBusy(true);try{await fn();}catch(e){showError(e);}finally{setBusy(false);}}
  if(!open)return <Button variant="secondary" label={kind==="gif"?"Choose a GIF from your library":"Choose music from your library"} onPress={()=>setOpen(true)}/>;
  return <Card>{collapsed?<Button small variant="ghost" label="Close picker" onPress={()=>setOpen(false)}/>:null}<Txt variant="heading">{kind==="gif"?"Find a GIF":"Choose music"}</Txt><Txt variant="small" tone="muted">{kind==="gif"?"Search your saved animated GIFs. Upload once to reuse a GIF in posts, stories and chats.":"Your own audio and licensed catalog tracks. Existing posts keep a copy when a library file is removed."}</Txt><Field label="Search titles and tags" value={query} onChangeText={setQuery} maxLength={60}/><Button small label="Search" onPress={()=>setSearch(query)}/>
    {q.isPending?<Loading/>:q.error?<Txt tone="danger">{q.error.message}</Txt>:!q.data?.items.length?<Txt tone="muted">No matching files. Add one below.</Txt>:q.data.items.map(item=><View key={item.id} style={{gap:8,paddingVertical:12}}>{kind==="gif"?<ContentMedia media={{id:item.id,kind:"gif",filename:item.filename,altText:item.altText,captions:"",url:item.url}}/>:previewId===item.id?<ContentMedia media={{id:item.id,kind:"audio",filename:item.filename,altText:item.altText,captions:"",url:item.url}}/>:<Button small label="Preview track" variant="secondary" onPress={()=>setPreviewId(item.id)}/>}<Txt variant="heading">{item.title}</Txt>{item.artist?<Txt variant="small">{item.artist}</Txt>:null}{item.licensed?<Txt variant="small">Licensed music · {item.licenseUrl}</Txt>:null}{onSelect?<Button small disabled={busy} variant="secondary" label={kind==="gif"?"Use GIF":"Use track"} onPress={()=>void run(async()=>{const selected=await mediaV10.file(item.id);onSelect({kind,filename:selected.filename,dataUrl:selected.dataUrl,altText:selected.altText,captions:""});})}/>:null}{manage&&item.mine?<Button small disabled={busy} variant="danger" label="Remove from library" onPress={()=>void run(async()=>{if(!await confirmAction("Remove library file?","Existing posts keep their own copy."))return;await mediaV10.remove(item.id);await client.invalidateQueries({queryKey:["mediaLibrary"]});})}/>:null}</View>)}
    <Txt variant="heading">Add {kind==="gif"?"a GIF":"audio you can share"}</Txt><Field label="Title" value={title} onChangeText={setTitle} maxLength={120}/>{kind==="audio"?<Field label="Artist" value={artist} onChangeText={setArtist} maxLength={120}/>:null}<Field label="Search tags" value={tags} onChangeText={setTags} maxLength={200}/><Button small variant="secondary" label={file?`Replace ${file.filename}`:"Choose file"} disabled={busy} onPress={()=>void run(async()=>{const picked=await pickContentFile(kind,kind==="gif"?"image/gif":"audio/*");if(picked)setFile(picked);})}/><Chip label="I have permission to share and reuse this file" selected={rights} onPress={()=>setRights(!rights)}/>{manage&&kind==="audio"?<Field label="Licensed catalog (site team only)" hint="Leave blank to keep this file private. The license must permit all uses offered by Kamino." placeholder="HTTPS license document" value={license} onChangeText={setLicense} maxLength={500}/>:null}<Button disabled={busy||!rights||!file||!title.trim()} label={busy?"Saving…":"Save to library"} onPress={()=>void run(async()=>{if(!file)return;await mediaV10.save({kind,title,artist,tags,dataUrl:file.dataUrl,filename:file.filename,altText:title,rightsConfirmed:true,licensed:!!license,licenseUrl:license});setFile(null);setTitle("");setRights(false);await client.invalidateQueries({queryKey:["mediaLibrary"]});notify("Library updated","Your file is available to reuse.");})}/>
  </Card>;
}
