import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { View } from "react-native";
import { router } from "expo-router";
import { contentApi, POST_EMOJI } from "@/lib/content-v9";
import { Button, Field, PressableScale, Txt } from "@/components/ui";
import { showError } from "@/lib/errors";
import { useTheme } from "@/theme";
import { ContentMedia } from "./ContentMedia";

export function PostContentTools({postId,story=false}:{postId:number;story?:boolean}){
  const theme=useTheme(),client=useQueryClient(),q=useQuery({queryKey:["postContent",postId],queryFn:()=>contentApi.post(postId)}),[history,setHistory]=useState(false),[analytics,setAnalytics]=useState(false);
  const stats=useQuery({queryKey:["postAnalytics",postId],queryFn:()=>contentApi.analytics(postId),enabled:analytics});
  useEffect(()=>{void contentApi.view(postId).catch(()=>undefined);},[postId]);
  async function run(fn:()=>Promise<unknown>){try{await fn();await client.invalidateQueries({queryKey:["postContent",postId]});}catch(e){showError(e);}}
  if(!q.data)return null;const d=q.data;
  return <View style={{gap:12}}>{story?<StoryInteractions postId={postId}/>:null}{d.media.map(m=><ContentMedia media={m} key={m.id}/>)}<View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{POST_EMOJI.map(emoji=>{const r=d.reactions.find(x=>x.emoji===emoji);return <PressableScale key={emoji} accessibilityLabel={`React ${emoji}`} accessibilityState={{selected:r?.mine??false}} onPress={()=>void run(()=>contentApi.react(postId,emoji))} style={{minHeight:44,minWidth:48,padding:10,borderWidth:1,borderColor:r?.mine?theme.accent:theme.border,borderRadius:24,backgroundColor:r?.mine?theme.tint:theme.surface}}><Txt>{emoji} {r?.count||""}</Txt></PressableScale>;})}</View><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}><Button small variant="secondary" label={d.following?"Following thread":"Follow thread"} onPress={()=>void run(()=>contentApi.personal(postId,{following:!d.following}))}/><Button small variant="secondary" label={d.muted?"Unmute post":"Mute post"} onPress={()=>void run(()=>contentApi.personal(postId,{muted:!d.muted}))}/><Button small variant="secondary" label={d.hidden?"Show in feed":"Hide from my feed"} onPress={()=>void run(()=>contentApi.personal(postId,{hidden:!d.hidden}))}/></View>{d.history.length?<><Button small variant="ghost" label={history?"Close edit history":`Edit history · ${d.history.length} versions`} onPress={()=>setHistory(!history)}/>{history?d.history.map(h=><View key={h.id} style={{padding:12,backgroundColor:theme.surfaceAlt,borderRadius:16,gap:6}}><Txt variant="caption" tone="muted">{new Date(h.editedAt).toLocaleString()}</Txt><Txt variant="heading">{h.title}</Txt><Txt>{h.body}</Txt></View>):null}</>:null}{d.canManage?<View style={{gap:10,padding:14,borderRadius:16,borderWidth:1,borderColor:theme.border}}><Txt variant="heading">Sharing & audience</Txt><Button variant="secondary" small label={d.sharingAllowed?"Sharing allowed · Turn off":"Sharing disabled · Turn on"} onPress={()=>void run(()=>contentApi.rules(postId,!d.sharingAllowed,d.commentRule as "members"|"followers"|"none"))}/><View style={{flexDirection:"row",flexWrap:"wrap",gap:6}}>{(["members","followers","none"] as const).map(rule=><Button small variant={d.commentRule===rule?"primary":"secondary"} key={rule} label={rule==="none"?"Closed":rule==="followers"?"Followers":"Members"} onPress={()=>void run(()=>contentApi.rules(postId,d.sharingAllowed,rule))}/>)}</View><Button small variant="secondary" label="Post analytics" onPress={()=>setAnalytics(!analytics)}/>{stats.data?<View style={{flexDirection:"row",flexWrap:"wrap",gap:14}}>{Object.entries(stats.data).map(([k,v])=><View key={k}><Txt variant="title">{v}</Txt><Txt variant="caption" tone="muted">{k}</Txt></View>)}</View>:null}</View>:null}</View>;
}

export function StoryInteractions({postId}:{postId:number}){
  const q=useQuery({queryKey:["storyTools",postId],queryFn:()=>contentApi.story(postId)}),client=useQueryClient(),[answer,setAnswer]=useState("");
  async function submit(optionIndex?:number){try{await contentApi.respond(postId,optionIndex===undefined?{answer}:{optionIndex});setAnswer("");await client.invalidateQueries({queryKey:["storyTools",postId]});}catch(e){showError(e);}}
  if(!q.data)return null;const d=q.data;return <View style={{gap:12}}><View style={{minHeight:280,backgroundColor:d.background,borderRadius:20,padding:24,alignItems:"center",justifyContent:"center",gap:16}}><Txt style={{fontSize:44,lineHeight:52}}>{d.sticker}</Txt><Txt variant="title" style={{textAlign:"center",color:"#fff"}}>{d.overlayText}</Txt><View style={{flexDirection:"row",flexWrap:"wrap",gap:10}}>{d.mentions.map(h=><Txt key={h} accessibilityRole="link" style={{color:"#fff"}} onPress={()=>router.push(`/profile/${h}`)}>@{h}</Txt>)}</View></View>{d.pollOptions.map((option,i)=><Button key={i} variant={d.mine?.optionIndex===i?"primary":"secondary"} label={`${option} · ${d.responses.find(r=>r.option_index===i)?.count??0}`} onPress={()=>void submit(i)}/>)}{d.question?<><Txt variant="heading">{d.question}</Txt><Field value={answer} onChangeText={setAnswer} maxLength={500} label="Your private answer to the creator" multiline/><Button disabled={!answer.trim()} label="Send answer" onPress={()=>void submit()}/>{d.answers.map((a,i)=><Txt key={i}>{a}</Txt>)}</>:null}</View>;
}
