import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { View } from 'react-native';
import { socialEvents } from '@/api/social-events-v10';
import { contentV9 } from '@/api/content-v9';
import { Screen, Card, Txt, Button, Field, Chip, Loading } from '@/components/ui';
import { showError } from '@/lib/errors';
import { confirmAction } from '@/components/community/platform';
export default function GroupSettings(){
  const params=useLocalSearchParams<{roomId:string}>(),roomId=Number(params.roomId),q=useQuery({queryKey:['groupManagement',roomId],queryFn:()=>socialEvents.group(roomId)});
  const [handle,setHandle]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await q.refetch();}catch(e){showError(e);}finally{setBusy(false);}};
  if(q.isPending)return <Loading/>;if(q.error||!q.data)return <Screen><Txt tone="danger">{q.error?.message}</Txt></Screen>;const group=q.data,admin=['owner','coadmin'].includes(group.role);
  return <Screen refreshing={q.isRefetching} onRefresh={()=>void q.refetch()}><Txt variant="title">{group.name}</Txt><Txt tone="muted">Your role: {group.role}. Moderators can pin messages and remove members. Co-admins can also invite and rename.</Txt><Button label="Open conversation" onPress={()=>router.push(`/chat/${roomId}`)}/>{admin?<><Card><Field label="Group name" placeholder={group.name} value={name} onChangeText={setName} maxLength={70}/><Button label="Save name" busy={busy} onPress={()=>void act(()=>contentV9.updateGroup({roomId,name}))}/></Card><Card><Field label="Invite a member" placeholder="@username" value={handle} onChangeText={setHandle} autoCapitalize="none"/><Button label="Send invitation" busy={busy} onPress={()=>void act(async()=>{await socialEvents.inviteGroup(roomId,handle);setHandle('');})}/><Txt variant="small" tone="muted">They can read the conversation after accepting.</Txt></Card></>:null}<Card><Txt variant="heading">Members</Txt>{group.people.map(p=><View key={p.userId} style={{gap:8}}><Txt>{p.name} · {p.role}</Txt>{group.role==='owner'&&p.role!=='owner'?<View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{(['member','moderator','coadmin'] as const).map(role=><Chip key={role} label={role} selected={role===p.role} onPress={()=>{if(!busy)void act(()=>socialEvents.groupRole(roomId,p.userId,role));}}/>)}</View>:null}{p.role==='member'&&group.role!=='member'||group.role==='owner'&&p.role!=='owner'?<Button small variant="secondary" label="Remove member" busy={busy} onPress={()=>confirmAction(`Remove ${p.name}?`,'They will lose access to the group.',()=>void act(()=>contentV9.updateGroup({roomId,removeUserId:p.userId})))}/>:null}</View>)}</Card>{admin&&group.invitations.length?<Card><Txt variant="heading">Pending invitations</Txt>{group.invitations.map(i=><View key={i.id} style={{gap:8}}><Txt>{i.name}</Txt><Button small variant="secondary" label="Cancel invitation" busy={busy} onPress={()=>void act(()=>socialEvents.cancelGroupInvite(roomId,i.id))}/></View>)}</Card>:null}<Button label="Leave group" variant="secondary" busy={busy} onPress={()=>confirmAction('Leave this group?','Ownership passes to an administrator or remaining member.',()=>void act(async()=>{await contentV9.updateGroup({roomId,leave:true});router.replace('/connections');}))}/></Screen>;
}
