import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Image } from 'expo-image';
import * as Linking from 'expo-linking';
import { useState } from 'react';
import { Alert,FlatList,Pressable,View } from 'react-native';
import { communityV9,type ExpandedEvent,type EventInput } from '@/api/community-v9';
import { Button,Card,Chip,EmptyState,ErrorState,Field,Loading,Sheet,Txt } from '@/components/ui';
import { ChallengePanel } from '@/components/ChallengePanel';
import { formatDateTime,parseLocalDateTime } from '@/lib/format';
import { showError } from '@/lib/errors';
import { space,useTheme } from '@/theme';
function localInput(value:string|null){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16).replace('T',' ');}
export function CommunityEventsV9({slug}:{slug:string}){
  const theme=useTheme();const q=useQuery({queryKey:['events',slug],queryFn:()=>communityV9.events(slug)});
  const [editor,setEditor]=useState<ExpandedEvent|'new'|null>(null),[busy,setBusy]=useState(false),[calendar,setCalendar]=useState(false),[month,setMonth]=useState(()=>new Date()),[date,setDate]=useState<number|null>(null),[attendees,setAttendees]=useState<{title:string;rows:Awaited<ReturnType<typeof communityV9.attendees>>}|null>(null);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await q.refetch();}catch(e){showError(e);}finally{setBusy(false);}};
  if(q.isPending)return <Loading/>;if(q.error||!q.data)return <ErrorState error={q.error} onRetry={()=>void q.refetch()}/>;
  const data=q.data,member=data.member?.status==='active',lead=!!member&&['agent','leader'].includes(data.member!.role);
  const addCalendar=async(ev:ExpandedEvent)=>{const stamp=(s:string)=>new Date(s).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const params=new URLSearchParams({action:'TEMPLATE',text:ev.title,details:ev.body,location:ev.location||ev.onlineUrl,dates:`${stamp(ev.startsAt)}/${stamp(ev.endsAt||new Date(new Date(ev.startsAt).getTime()+3600000).toISOString())}`});await Linking.openURL(`https://calendar.google.com/calendar/render?${params.toString()}`);};
  const shown=date!==null?data.events.filter(e=>{const d=new Date(e.startsAt);return d.getFullYear()===month.getFullYear()&&d.getMonth()===month.getMonth()&&d.getDate()===date;}):data.events;
  const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),first=new Date(month.getFullYear(),month.getMonth(),1).getDay();
  return <><FlatList data={shown} keyExtractor={e=>String(e.id)} contentContainerStyle={{padding:space.lg,gap:space.md,flexGrow:1}} refreshing={q.isRefetching} onRefresh={()=>void q.refetch()} ListHeaderComponent={<View style={{gap:space.md}}><Txt variant="heading">Events & challenges</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}><Button small variant="secondary" label={calendar?'List view':'Month view'} onPress={()=>{setCalendar(v=>!v);setDate(null);}}/>{data.canCreate?<Button small label="Create event" onPress={()=>setEditor('new')}/>:null}</View>{calendar?<Card><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Button small variant="ghost" label="Previous" onPress={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));setDate(null);}}/><Txt variant="small">{month.toLocaleDateString(undefined,{month:'short',year:'numeric'})}</Txt><Button small variant="ghost" label="Next" onPress={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));setDate(null);}}/></View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['S','M','T','W','T','F','S'].map((d,i)=><View key={i} style={{width:'14.28%',alignItems:'center',paddingVertical:space.sm}}><Txt variant="caption" tone="muted">{d}</Txt></View>)}{Array.from({length:first},(_,i)=><View key={`b-${i}`} style={{width:'14.28%'}}/>)}{Array.from({length:days},(_,i)=>{const day=i+1,has=data.events.some(ev=>{const d=new Date(ev.startsAt);return d.getFullYear()===month.getFullYear()&&d.getMonth()===month.getMonth()&&d.getDate()===day&&ev.status!=='cancelled';});return <Pressable key={day} accessibilityRole="button" accessibilityLabel={`${month.toLocaleDateString(undefined,{month:'long'})} ${day}${has?', has events':''}`} onPress={()=>setDate(v=>v===day?null:day)} style={{width:'14.28%',minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:date===day?theme.tint:'transparent'}}><Txt variant="small">{day}{has?' •':''}</Txt></Pressable>;})}</View>{date!==null?<Button small variant="ghost" label="Show all events" onPress={()=>setDate(null)}/>:null}</Card>:null}</View>}
    renderItem={({item:ev})=><Card>{ev.imageUrl?<Image source={{uri:ev.imageUrl}} accessibilityLabel={`${ev.title} event banner`} contentFit="cover" style={{height:160,borderRadius:12,width:'100%'}}/>:null}<View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}><Chip label={ev.kind==='challenge'?'Challenge':ev.venueKind==='in_person'?'In person':'Online'}/>{ev.status==='cancelled'?<Chip label="Cancelled" tone="danger"/>:null}{ev.recurrence!=='none'?<Chip label={`Repeats ${ev.recurrence}`}/>:null}</View><Txt variant="heading">{ev.title}</Txt><Txt tone="muted">{ev.body}</Txt><Txt variant="small">{formatDateTime(ev.startsAt)}{ev.endsAt?` – ${formatDateTime(ev.endsAt)}`:''}</Txt>{ev.location?<Txt tone="muted">📍 {ev.location}</Txt>:null}{ev.onlineUrl&&ev.status!=='cancelled'?<Button small variant="ghost" label="Open event link" onPress={()=>void act(()=>Linking.openURL(ev.onlineUrl))}/>:null}{ev.kind==='challenge'?<ChallengePanel slug={slug} event={ev} isMember={member} isLeader={lead}/>:null}<View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{member&&ev.status!=='cancelled'?<><Button small busy={busy} label={ev.myResponse==='going'?'Going ✓':'Going'} variant={ev.myResponse==='going'?'primary':'secondary'} onPress={()=>void act(()=>communityV9.rsvp(slug,ev.id,ev.myResponse==='going'?'none':'going'))}/><Button small busy={busy} label={ev.myResponse==='interested'?'Interested ✓':'Interested'} variant={ev.myResponse==='interested'?'primary':'secondary'} onPress={()=>void act(()=>communityV9.rsvp(slug,ev.id,ev.myResponse==='interested'?'none':'interested'))}/></>:null}<Button small variant="secondary" label="Google Calendar" onPress={()=>void act(()=>addCalendar(ev))}/>{member?<Button small variant="ghost" label={`${ev.rsvpCount} going · ${ev.interestedCount} interested`} onPress={()=>void act(async()=>setAttendees({title:ev.title,rows:await communityV9.attendees(slug,ev.id)}))}/>:<Txt variant="small" tone="muted">{ev.rsvpCount} going · {ev.interestedCount} interested</Txt>}{member&&ev.chatRoomId?<Button small variant="secondary" label={ev.liveRoomId?'Event live room':'Event chat'} onPress={()=>router.push(`/chat/${ev.chatRoomId}`)}/>:null}</View>{ev.canEdit?<View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{ev.status!=='cancelled'?<><Button small variant="secondary" label="Edit" onPress={()=>setEditor(ev)}/><Button small variant="secondary" label="Cancel event" onPress={()=>Alert.alert(`Cancel ${ev.title}?`,'Attendees will be notified.',[{text:'Keep event',style:'cancel'},{text:'Cancel event',style:'destructive',onPress:()=>void act(()=>communityV9.manageEvent(slug,ev.id,'cancel'))}])}/></>:null}<Button small variant="danger" label="Delete" onPress={()=>Alert.alert(`Delete ${ev.title}?`,'This removes the event and RSVPs.',[{text:'Keep event',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void act(()=>communityV9.manageEvent(slug,ev.id,'delete'))}])}/></View>:null}</Card>}
    ListEmptyComponent={<EmptyState icon="calendar-outline" title="No events yet" body={date!==null?'No plans on this date.':'The next community gathering starts here.'}/>}/>
    <Sheet visible={!!editor} title={editor==='new'?'Create event':'Edit event'} onClose={()=>setEditor(null)}>{editor?<EventEditor key={editor==='new'?'new':editor.id} slug={slug} event={editor==='new'?undefined:editor} busy={busy} onSave={d=>act(async()=>{await communityV9.saveEvent(d);setEditor(null);})}/>:null}</Sheet><Sheet visible={!!attendees} title={`Attendees · ${attendees?.title??''}`} onClose={()=>setAttendees(null)}>{attendees?.rows.length?attendees.rows.map(p=><Card key={p.userId} onPress={()=>{setAttendees(null);router.push(`/profile/${p.handle}`);}}><Txt>{p.nickname}</Txt><Txt variant="small" tone="muted">{p.response}</Txt></Card>):<Txt tone="muted">Be the first to make plans.</Txt>}</Sheet></>;
}
function EventEditor({slug,event,busy,onSave}:{slug:string;event?:ExpandedEvent;busy:boolean;onSave:(d:EventInput)=>Promise<void>}){
  const [title,setTitle]=useState(event?.title??''),[body,setBody]=useState(event?.body??''),[starts,setStarts]=useState(localInput(event?.startsAt??null)),[ends,setEnds]=useState(localInput(event?.endsAt??null)),[kind,setKind]=useState<'event'|'challenge'>(event?.kind??'event'),[venue,setVenue]=useState<'online'|'in_person'>(event?.venueKind==='in_person'?'in_person':'online'),[url,setUrl]=useState(event?.onlineUrl??''),[location,setLocation]=useState(event?.location??''),[image,setImage]=useState(event?.imageUrl??''),[repeat,setRepeat]=useState<EventInput['recurrence']>('none'),[count,setCount]=useState('4'),[chat,setChat]=useState(false),[live,setLive]=useState(false);
  const submit=()=>{const startsAt=parseLocalDateTime(starts),endsAt=ends?parseLocalDateTime(ends):undefined;if(!startsAt||ends&&!endsAt){showError(new Error('Write dates like 2026-10-31 19:30.'));return;}void onSave({slug,id:event?.id,title,body,kind,startsAt,endsAt:endsAt??undefined,venueKind:venue,onlineUrl:url,location,imageUrl:image,recurrence:repeat,repeatCount:Number(count),createChat:chat,createLive:live});};
  return <View style={{gap:space.md}}><Field label="Title" value={title} onChangeText={setTitle} maxLength={120}/><Field label="Details" value={body} onChangeText={setBody} multiline maxLength={3000}/>{!event?<View style={{flexDirection:'row',gap:space.sm}}>{(['event','challenge'] as const).map(v=><Chip key={v} label={v} selected={kind===v} onPress={()=>setKind(v)}/>)}</View>:null}<Field label="Starts (your local time)" value={starts} onChangeText={setStarts} placeholder="2026-10-31 19:30"/><Field label="Ends (optional)" value={ends} onChangeText={setEnds} placeholder="2026-10-31 21:00"/><View style={{flexDirection:'row',gap:space.sm}}><Chip label="Online" selected={venue==='online'} onPress={()=>setVenue('online')}/><Chip label="In person" selected={venue==='in_person'} onPress={()=>setVenue('in_person')}/></View><Field label="Online event link" value={url} onChangeText={setUrl} autoCapitalize="none" keyboardType="url" placeholder="https://…"/><Field label="Location" value={location} onChangeText={setLocation} maxLength={300} placeholder="Venue or meeting point"/><Field label="Banner image link" value={image} onChangeText={setImage} autoCapitalize="none" keyboardType="url" placeholder="https://…"/>{!event?<><Txt variant="label">Repeats</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(['none','daily','weekly','monthly'] as const).map(v=><Chip key={v} label={v==='none'?'One time':v} selected={repeat===v} onPress={()=>setRepeat(v)}/>)}</View>{repeat!=='none'?<><Field label="Occurrences (1–12)" value={count} onChangeText={setCount} keyboardType="number-pad"/><Txt variant="caption" tone="muted">Repeats keep a fixed UTC time. Edit dates that cross daylight-saving changes.</Txt></>:null}<Chip label="Create event chat" selected={chat} onPress={()=>setChat(v=>!v)}/><Chip label="Create scheduled live room" selected={live} onPress={()=>setLive(v=>!v)}/></>:null}<Button busy={busy} label={event?'Save event':'Publish event'} onPress={submit}/></View>;
}
