import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { View } from 'react-native';
import { socialEvents } from '@/api/social-events-v10';
import { Card, Txt, Button, Field, Loading } from '@/components/ui';
import { showError } from '@/lib/errors';
export function EventParticipationV10({slug,eventId}:{slug:string;eventId:number}){
  const q=useQuery({queryKey:['eventParticipation',eventId],queryFn:()=>socialEvents.event(slug,eventId)}),[body,setBody]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await q.refetch();}catch(e){showError(e);}finally{setBusy(false);}};
  return <Card><Txt variant="heading">Event updates & attendance</Txt>{q.isPending?<Loading/>:q.error?<Txt tone="danger">{q.error.message}</Txt>:q.data?<>{q.data.mine?<><Txt selectable>Attendance pass: {q.data.mine.code}</Txt><Txt variant="small">Status: {q.data.mine.state}</Txt></>:null}{q.data.status!=='cancelled'?<><Button small variant="secondary" label={q.data.mine?'Refresh pass':'Get attendance pass'} busy={busy} onPress={()=>void act(()=>socialEvents.pass(slug,eventId))}/><Txt variant="caption" tone="muted">Requires a Going RSVP and any required ticket access. This attendance pass does not charge you.</Txt><Field label="Share an event update" value={body} onChangeText={setBody} multiline maxLength={2000}/><Button small label="Post update" busy={busy} onPress={()=>void act(async()=>{await socialEvents.eventPost(slug,eventId,body);setBody('');})}/></>:null}{q.data.timeline.map(t=><View key={t.id} style={{gap:6}}><Txt variant="label">{t.name}</Txt><Txt>{t.body}</Txt><Txt variant="caption" tone="muted">{new Date(t.createdAt).toLocaleString()}</Txt>{t.canDelete?<Button small variant="ghost" label="Remove update" busy={busy} onPress={()=>void act(()=>socialEvents.deleteEventPost(slug,eventId,t.id))}/>:null}</View>)}{q.data.organizer?<><Field label="Attendee pass code" value={code} onChangeText={setCode} autoCapitalize="none" placeholder="Paste the attendee’s code"/><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><Button small label="Check in" disabled={q.data.status==='cancelled'} busy={busy} onPress={()=>void act(()=>socialEvents.checkIn(slug,eventId,code))}/><Button small label="Undo check-in" variant="secondary" disabled={q.data.status==='cancelled'} busy={busy} onPress={()=>void act(()=>socialEvents.checkIn(slug,eventId,code,true))}/></View><Txt>{q.data.passes.filter(p=>p.state==='checked_in').length} checked in · {q.data.passes.length} passes</Txt>{q.data.passes.map(p=><Txt key={p.id} variant="small">{p.name} · {p.state}</Txt>)}</>:null}</>:null}</Card>;
}
