import {useQuery} from '@tanstack/react-query';
import {router} from 'expo-router';
import {setStringAsync} from 'expo-clipboard';
import {Alert,View} from 'react-native';
import Svg,{Circle,Line,Text as SvgText} from 'react-native-svg';
import {platform} from '@/api/platform-v9';
import {Card,Txt,Button} from './ui';
import {useTheme} from '@/theme';
export function PeopleMatching(){const theme=useTheme(),q=useQuery({queryKey:['peopleMatching'],queryFn:platform.matching});if(!q.data)return null;const {people,interests}=q.data;const points=interests.slice(0,8).map((label,i,a)=>({label,x:160+Math.cos(i*2*Math.PI/a.length)*110,y:125+Math.sin(i*2*Math.PI/a.length)*90}));return <Card><Txt variant="heading">Find my people</Txt><Txt tone="muted">Matches share your chosen interests. Personalize an introduction before sending it.</Txt>{points.length?<Svg viewBox="0 0 320 250" width="100%" height={250} accessibilityLabel={`Your interest graph: ${interests.join(', ')}`}><Circle cx={160} cy={125} r={22} fill={theme.accent}/><SvgText x={160} y={129} fill="white" textAnchor="middle">You</SvgText>{points.map(p=><ViewNodes key={p.label} {...p} color={theme.accent} textColor={theme.text}/>)}</Svg>:<Txt>Choose interests in your privacy dashboard to find matches.</Txt>}{people.map(p=><View key={p.userId} style={{gap:8,paddingTop:10}}><Button variant="ghost" label={`${p.name} · @${p.handle}`} onPress={()=>router.push(`/profile/${p.handle}` as never)}/><Txt>{p.shared.join(' · ')}</Txt><Txt tone="muted">{p.introduction}</Txt><Button small variant="secondary" label="Copy introduction" onPress={()=>void setStringAsync(p.introduction).catch(()=>Alert.alert('Copy failed','Try again.'))}/></View>)}{!people.length?<Txt tone="muted">No matches yet. More members with shared interests will appear as the community grows.</Txt>:null}</Card>;}
function ViewNodes({label,x,y,color,textColor}:{label:string;x:number;y:number;color:string;textColor:string}){return <><Line x1={160} y1={125} x2={x} y2={y} stroke={color} opacity={0.3}/><Circle cx={x} cy={y} r={22} fill={color} opacity={0.1}/><SvgText x={x} y={y+4} fill={textColor} fontSize={11} textAnchor="middle">{label}</SvgText></>;}
