import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { View } from 'react-native';
import { communityV9 } from '@/api/community-v9';
import { Button,Card,Chip,Txt } from '@/components/ui';
import { showError } from '@/lib/errors';
import { space } from '@/theme';
export function StageControlsV9({roomId,userId}:{roomId:number;userId:string}){
  const q=useQuery({queryKey:['live-stage',roomId],queryFn:()=>communityV9.stage(roomId),refetchInterval:2500});const [busy,setBusy]=useState(false),[open,setOpen]=useState(false);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await q.refetch();}catch(e){showError(e);}finally{setBusy(false);}};
  if(!q.data)return null;const data=q.data,me=data.participants.find(p=>p.userId===userId);
  return <Card><Button small variant="ghost" label={`${data.enabled?'Live stage':'Room controls'}${data.locked?' · Locked':''}`} onPress={()=>setOpen(v=>!v)}/>{open||data.enabled?<><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{data.host?<><Button small variant="secondary" busy={busy} label={data.enabled?'Open conversation':'Enable stage'} onPress={()=>void act(()=>communityV9.configureStage({roomId,enabled:!data.enabled}))}/><Button small variant="secondary" busy={busy} label={data.locked?'Unlock':'Lock room'} onPress={()=>void act(()=>communityV9.configureStage({roomId,locked:!data.locked}))}/></>:null}{data.enabled&&me?.role==='listener'?<Button small busy={busy} label={me.raised?'Lower hand':'Raise hand'} onPress={()=>void act(()=>communityV9.stageAction(roomId,me.raised?'lower':'raise'))}/>:null}{['❤️','👏','🔥','🎉'].map(emoji=><Chip key={emoji} label={emoji} onPress={()=>void act(()=>communityV9.reactStage(roomId,emoji))}/>)}</View>{data.scheduledAt?<Txt variant="caption" tone="muted">Scheduled {new Date(data.scheduledAt).toLocaleString()}</Txt>:null}<Txt variant="small" tone="muted">{me?.muted?'Your microphone is muted by the host.':data.enabled&&me?.role==='listener'?'You are listening. Raise your hand to speak.':''} {data.reactions.map(r=>r.emoji).join(' ')}</Txt>{data.participants.map(p=><View key={p.userId} style={{gap:space.sm}}><Txt>{p.nickname}{p.raised?' ✋':''} · {p.cohost?'Co-host · ':''}{p.role}{p.muted?' · Muted':''}</Txt>{data.host&&p.role!=='host'&&p.userId!==userId?<View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}><Button small variant="secondary" busy={busy} label={p.cohost?'Remove co-host':'Make co-host'} onPress={()=>void act(()=>communityV9.stageAction(roomId,p.cohost?'uncohost':'cohost',p.userId))}/>{p.role==='listener'?<Button small label="Invite to speak" busy={busy} onPress={()=>void act(()=>communityV9.stageAction(roomId,'speaker',p.userId))}/>:<Button small variant="secondary" label="Move to audience" busy={busy} onPress={()=>void act(()=>communityV9.stageAction(roomId,'listener',p.userId))}/>}<Button small variant="secondary" label={p.muted?'Unmute':'Mute'} busy={busy} disabled={p.muted&&p.role==='listener'} onPress={()=>void act(()=>communityV9.stageAction(roomId,p.muted?'unmute':'mute',p.userId))}/><Button small variant="danger" label="Remove" busy={busy} onPress={()=>void act(()=>communityV9.stageAction(roomId,'remove',p.userId))}/></View>:null}</View>)}</>:null}</Card>;
}
