import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { GradientButton, OutlineButton } from "@/components/k";
import { fieldClass } from "@/components/community/sheet";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
import { postContentTools, reactToPost, setPostPersonal, setPostContentRules, postAnalytics, recordPostView, getStoryTools, respondToStory } from "@/lib/kamino/content-v9";
import { POST_EMOJI } from "@/lib/kamino/content-rules";

export function ContentMedia({media}:{media:{id:number;kind:string;url:string;altText:string;captions:string;filename:string}}){
  if(media.kind==="video"||media.kind==="short")return <figure className="space-y-2"><video controls playsInline preload="metadata" aria-label={media.altText||media.filename} className={`w-full rounded-card bg-black ${media.kind==="short"?"mx-auto max-h-[650px] max-w-[390px]":"max-h-[500px]"}`} src={media.url}>{media.captions?<track kind="captions" src={`${media.url}?captions=1`} srcLang="en" label="Captions" default/>:null}</video>{media.captions?<details className="text-sm text-muted"><summary>Transcript</summary><p className="whitespace-pre-wrap">{media.captions}</p></details>:null}</figure>;
  if(media.kind==="audio")return <figure className="rounded-card border border-border bg-surface-alt p-4"><p className="mb-2 font-bold">🎧 {media.filename}</p><audio controls preload="metadata" src={media.url} className="w-full" aria-label={media.altText||media.filename}/>{media.captions?<p className="mt-3 whitespace-pre-wrap text-sm">{media.captions}</p>:null}</figure>;
  if(media.kind==="file")return <a href={media.url} download className="k-focus block rounded-card border border-border p-4 font-semibold text-accent">📎 Download {media.filename}</a>;
  return <img src={media.url} alt={media.altText||media.filename} className="max-h-[500px] w-full rounded-card object-contain" loading="lazy"/>;
}

export function PostContentTools({postId,story=false}:{postId:number;story?:boolean}){
  const {user}=useCurrentUserState(),client=useQueryClient(),q=useQuery({queryKey:["postContent",postId],queryFn:()=>postContentTools({data:{postId}})});
  const [history,setHistory]=useState(false),[analytics,setAnalytics]=useState(false);
  const stats=useQuery({queryKey:["postAnalytics",postId],queryFn:()=>postAnalytics({data:{postId}}),enabled:analytics&&!!user});
  useEffect(()=>{if(user)void recordPostView({data:{postId}}).catch(()=>undefined);},[user,postId]);
  async function run(fn:()=>Promise<unknown>){try{await fn();await client.invalidateQueries({queryKey:["postContent",postId]});}catch(e){toast.error(e instanceof Error?e.message:"Please try again.");}}
  if(!q.data)return null;
  const d=q.data;
  return <section className="space-y-3" aria-label="Post media and thread controls">
    {d.hidden?<div className="rounded-card border border-border bg-surface-alt p-3 text-sm">You hid this post from your feeds. <button className="font-bold text-accent" onClick={()=>void run(()=>setPostPersonal({data:{postId,hidden:false}}))}>Undo</button></div>:null}
    {story?<StoryInteractions postId={postId}/>:null}
    {d.media.map(m=><ContentMedia key={m.id} media={m}/>)}
    <div className="flex flex-wrap gap-2">{POST_EMOJI.map(emoji=>{const reaction=d.reactions.find(r=>r.emoji===emoji);return <button key={emoji} type="button" disabled={!user} aria-label={`React ${emoji}`} aria-pressed={reaction?.mine??false} onClick={()=>void run(()=>reactToPost({data:{postId,emoji}}))} className={`k-focus min-h-10 rounded-full border px-3 text-base ${reaction?.mine?"border-accent bg-accent/10":"border-border bg-surface"}`}>{emoji}{reaction?` ${reaction.count}`:""}</button>;})}</div>
    {user?<div className="flex flex-wrap gap-2"><OutlineButton onClick={()=>void run(()=>setPostPersonal({data:{postId,following:!d.following}}))}>{d.following?"Following thread":"Follow thread"}</OutlineButton><OutlineButton onClick={()=>void run(()=>setPostPersonal({data:{postId,muted:!d.muted}}))}>{d.muted?"Unmute post":"Mute post"}</OutlineButton><OutlineButton onClick={()=>void run(()=>setPostPersonal({data:{postId,hidden:!d.hidden}}))}>{d.hidden?"Show in feed":"Hide from my feed"}</OutlineButton><OutlineButton onClick={()=>{void navigator.clipboard.writeText(location.href).then(()=>toast.success("Link copied")).catch(()=>toast.error("Could not copy the link."));}}>Copy link</OutlineButton></div>:null}
    {d.history.length?<><button className="k-focus min-h-10 rounded-full px-2 text-sm font-bold text-accent" onClick={()=>setHistory(!history)}>{history?"Close edit history":`Edit history · ${d.history.length} versions`}</button>{history?<div className="space-y-3 rounded-card border border-border p-4">{d.history.map(h=><details key={h.id}><summary className="cursor-pointer text-sm font-semibold">{new Date(h.editedAt).toLocaleString()} · {h.title}</summary><p className="mt-2 whitespace-pre-wrap text-sm">{h.body}</p></details>)}</div>:null}</>:null}
    {d.canManage?<details className="rounded-card border border-border p-4"><summary className="cursor-pointer font-bold">Audience, sharing & analytics</summary><div className="mt-3 space-y-3"><label className="flex gap-3 text-sm"><input type="checkbox" checked={d.sharingAllowed} onChange={e=>void run(()=>setPostContentRules({data:{postId,sharingAllowed:e.target.checked,commentRule:d.commentRule as "members"|"followers"|"none"}}))}/>Allow reposting and sharing in chat</label><label className="block text-sm font-semibold">Who can comment<select className={`${fieldClass} mt-2`} value={d.commentRule} onChange={e=>void run(()=>setPostContentRules({data:{postId,sharingAllowed:d.sharingAllowed,commentRule:e.target.value as "members"|"followers"|"none"}}))}><option value="members">Community members</option><option value="followers">My followers in this community</option><option value="none">Comments closed</option></select></label><OutlineButton onClick={()=>setAnalytics(!analytics)}>View post analytics</OutlineButton>{stats.data?<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(stats.data).map(([name,count])=><div key={name} className="rounded-tile bg-surface-alt p-3"><p className="text-xl font-extrabold">{count}</p><p className="text-xs capitalize text-muted">{name}</p></div>)}</div>:stats.error?<p className="text-sm text-danger">{stats.error.message}</p>:null}</div></details>:null}
  </section>;
}

export function StoryInteractions({postId}:{postId:number}){
  const {user}=useCurrentUserState(),client=useQueryClient(),[answer,setAnswer]=useState("");
  const q=useQuery({queryKey:["storyTools",postId],queryFn:()=>getStoryTools({data:{postId}})});
  async function submit(optionIndex?:number){try{await respondToStory({data:{postId,...(optionIndex===undefined?{answer}:{optionIndex})}});setAnswer("");await client.invalidateQueries({queryKey:["storyTools",postId]});toast.success("Response saved");}catch(e){toast.error(e instanceof Error?e.message:"Please try again.");}}
  if(!q.data)return null;const d=q.data;
  return <section className="overflow-hidden rounded-card border border-border" aria-label="Story"><div style={{background:d.background}} className="flex min-h-[280px] flex-col items-center justify-center gap-4 p-6 text-center text-white"><span className="text-5xl" aria-hidden>{d.sticker}</span><p className="whitespace-pre-wrap text-2xl font-extrabold">{d.overlayText}</p><div className="flex flex-wrap justify-center gap-2">{d.mentions.map(h=><a className="rounded-full bg-white/20 px-3 py-1 font-semibold" key={h} href={`/u/${h}`}>@{h}</a>)}</div></div>{d.pollOptions.length?<div className="space-y-2 p-4"><p className="font-bold">Story poll</p>{d.pollOptions.map((option,i)=><button key={i} disabled={!user} aria-pressed={d.mine?.optionIndex===i} className={`k-focus flex min-h-11 w-full justify-between rounded-tile border p-3 text-left ${d.mine?.optionIndex===i?"border-accent bg-accent/10":"border-border"}`} onClick={()=>void submit(i)}><span>{option}</span><span>{d.responses.find(r=>r.option_index===i)?.count??0}</span></button>)}</div>:null}{d.question?<div className="space-y-3 p-4"><p className="font-bold">{d.question}</p><textarea aria-label="Answer the story question" className={fieldClass} value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={500} placeholder="Your answer is sent privately to the creator"/><GradientButton disabled={!user||!answer.trim()} onClick={()=>void submit()}>Send answer</GradientButton>{d.answers.length?<details><summary>Responses · {d.answers.length}</summary>{d.answers.map((a,i)=><p className="mt-2 rounded-tile bg-surface-alt p-3 text-sm" key={i}>{a}</p>)}</details>:null}</div>:null}</section>;
}
