import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { GradientButton } from "@/components/k";
import { fieldClass } from "@/components/community/sheet";
import { createGroupChat } from "@/lib/kamino/content-v9";
export const Route=createFileRoute("/inbox-tools")({component:InboxTools});
function InboxTools(){const [name,setName]=useState(""),[handles,setHandles]=useState(""),[busy,setBusy]=useState(false);async function create(){setBusy(true);try{const r=await createGroupChat({data:{name,handles:handles.split(/[ ,\n]+/).map(s=>s.replace(/^@/,"").toLowerCase()).filter(Boolean)}});location.href=`/chats/${r.roomId}`;}catch(e){toast.error(e instanceof Error?e.message:"Could not create the group.");}finally{setBusy(false);}}return <AppShell back="/chats"><main className="mx-auto max-w-[620px] space-y-5 px-4 py-6"><div className="rounded-card bg-gradient-to-br from-violet-600 to-blue-500 p-6 text-white"><span className="text-4xl">💬</span><h1 className="mt-3 text-3xl font-extrabold">Start a group</h1><p className="mt-2 text-sm leading-6 text-white/90">A private place for your friends, independent of any community.</p></div><section className="space-y-4 rounded-card border border-border bg-surface p-5"><label className="block text-sm font-bold">Group name<input className={`${fieldClass} mt-2`} value={name} onChange={e=>setName(e.target.value)} maxLength={70} placeholder="Weekend art club"/></label><label className="block text-sm font-bold">Invite mutual followers<textarea className={`${fieldClass} mt-2 min-h-28`} value={handles} onChange={e=>setHandles(e.target.value)} placeholder="@mira, @jun, @leo"/></label><p className="text-sm leading-6 text-muted">Choose up to 19 friends who follow you back. Their messaging and invitation preferences are respected.</p><GradientButton full disabled={busy||name.trim().length<3||!handles.trim()} onClick={()=>void create()}>{busy?"Creating…":"Create private group"}</GradientButton></section></main></AppShell>;}
