import {createFileRoute} from '@tanstack/react-router';
import {useQuery} from '@tanstack/react-query';
import {useState} from 'react';
import {AppShell} from '@/components/app-shell';
import {Button} from '@/components/ui/button';
import * as api from '@/lib/kamino/search-v10';
import type {SearchKindV10,SearchResultV10} from '@/lib/kamino/search-v10-types';
export const Route=createFileRoute('/smart-search')({component:SmartSearch});
const box='rounded-2xl border border-border bg-surface p-4 space-y-3';
const field='w-full rounded-xl border border-border bg-elevated p-3 text-ink';
function Results({rows}:{rows:SearchResultV10[]}){return <div className="space-y-3">{rows.map(r=><a key={`${r.kind}:${r.id}`} href={r.href} className={`${box} block hover:border-violet`}><span className="text-xs font-bold uppercase text-muted">{r.kind}</span><h3 className="font-bold">{r.title}</h3><p className="break-words text-sm text-muted">{r.excerpt}</p></a>)}</div>;}
function SmartSearch(){
 const status=useQuery({queryKey:['semanticStatus'],queryFn:()=>api.getSemanticStatusV10()}),recommendations=useQuery({queryKey:['semanticRecommendations'],queryFn:()=>api.semanticRecommendationsV10()});
 const [query,setQuery]=useState(''),[kind,setKind]=useState<SearchKindV10|'all'>('all'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[results,setResults]=useState<SearchResultV10[]|null>(null);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await Promise.all([status.refetch(),recommendations.refetch()]);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
 return <AppShell title="Find your people" padded back><div className="mx-auto max-w-3xl space-y-5"><p className="text-muted">Describe an interest or the kind of community you want. Smart search compares meaning across posts, communities and profiles.</p>{status.isPending?<p role="status">Checking smart search…</p>:null}{status.error?<p role="alert">{status.error.message}</p>:status.data&&!status.data.configured?<section className={box}><h2 className="font-bold">Smart search is awaiting setup</h2><p className="text-sm text-muted">The app owner needs to connect an embedding provider. You can use the regular search now.</p><a href="/search" className="font-bold text-violet">Open search →</a></section>:null}<form className={box} onSubmit={e=>{e.preventDefault();void act(async()=>setResults((await api.semanticSearchV10({data:{query,kind,consent}})).results));}}><label className="block font-semibold">What are you looking for?<textarea className={`${field} mt-2`} value={query} onChange={e=>setQuery(e.target.value)} maxLength={800} placeholder="People who enjoy manga and drawing" required/></label><label className="block text-sm">Look in<select className={`${field} mt-2`} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="all">Everything</option><option value="post">Posts</option><option value="community">Communities</option><option value="person">People</option></select></label><label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to send this search text, and my chosen interests if I enable recommendations, to the configured AI provider.</span></label><Button disabled={!status.data?.configured||!consent||busy||query.trim().length<2}>{busy?'Searching…':'Search by meaning'}</Button></form>{error?<p role="alert" className="text-danger">{error}</p>:null}{results?<section className="space-y-3"><h2 className="text-lg font-bold">Search results</h2>{!results.length?<p className="text-muted">No accessible indexed matches yet. Try a different phrase or regular search.</p>:<Results rows={results}/>}</section>:null}<section className={box}><h2 className="font-bold">Recommendations from your interests</h2><p className="text-sm text-muted">Turn this on to match the interests saved in your profile. Turning it off removes your saved interest vector.</p><Button variant="secondary" disabled={busy||(!status.data?.personalized&&(!consent||!status.data?.configured))} onClick={()=>void act(()=>api.setSemanticPersonalizationV10({data:{enabled:!status.data?.personalized,consent}}))}>{status.data?.personalized?'Turn off recommendations':'Enable recommendations'}</Button>{recommendations.error?<p role="alert">{recommendations.error.message}</p>:null}{recommendations.data?.enabled?<Results rows={recommendations.data.results}/>:null}</section></div></AppShell>;
}
