/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAnalyticsRouteImport } from './routes/admin-analytics'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as CaptchaRouteImport } from './routes/captcha'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ChildSafetyRouteImport } from './routes/child-safety'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ContentStudioRouteImport } from './routes/content-studio'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DiscoverPlusRouteImport } from './routes/discover-plus'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InboxToolsRouteImport } from './routes/inbox-tools'
import { Route as KitRouteImport } from './routes/kit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MeRouteImport } from './routes/me'
import { Route as MediaLibraryRouteImport } from './routes/media-library'
import { Route as NewRouteImport } from './routes/new'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyDashboardRouteImport } from './routes/privacy-dashboard'
import { Route as ProfileStoriesRouteImport } from './routes/profile-stories'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShortVideosRouteImport } from './routes/short-videos'
import { Route as SmartSearchRouteImport } from './routes/smart-search'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSafetyRouteImport } from './routes/admin/safety'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as CSlugRouteImport } from './routes/c/$slug'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as ChatsRoomIdRouteImport } from './routes/chats/$roomId'
import { Route as GroupsRoomIdRouteImport } from './routes/groups/$roomId'
import { Route as InviteCodeRouteImport } from './routes/invite/$code'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1JobsRouteImport } from './routes/api/v1/jobs'
import { Route as CSlugIndexRouteImport } from './routes/c/$slug/index'
import { Route as CSlugChatsRouteImport } from './routes/c/$slug/chats'
import { Route as CSlugEventsRouteImport } from './routes/c/$slug/events'
import { Route as CSlugFilesRouteImport } from './routes/c/$slug/files'
import { Route as CSlugMembersRouteImport } from './routes/c/$slug/members'
import { Route as CSlugModRouteImport } from './routes/c/$slug/mod'
import { Route as CSlugRankRouteImport } from './routes/c/$slug/rank'
import { Route as CSlugToolsRouteImport } from './routes/c/$slug/tools'
import { Route as CSlugWikiRouteImport } from './routes/c/$slug/wiki'
import { Route as ApiV1AuthMobileCallbackRouteImport } from './routes/api/v1/auth/mobile-callback'
import { Route as ApiV1AuthMobileStartRouteImport } from './routes/api/v1/auth/mobile-start'
import { Route as ApiV1BillingStripeWebhookRouteImport } from './routes/api/v1/billing/stripe-webhook'
import { Route as ApiV1ContentMediaMediaIdRouteImport } from './routes/api/v1/content-media/$mediaId'
import { Route as ApiV1LibraryMediaLibraryIdRouteImport } from './routes/api/v1/library-media/$libraryId'
import { Route as ApiV1ProfileStoryMediaStoryIdRouteImport } from './routes/api/v1/profile-story-media/$storyId'
import { Route as ApiV1RpcNameRouteImport } from './routes/api/v1/rpc/$name'
import { Route as CSlugPPostIdRouteImport } from './routes/c/$slug/p/$postId'
import { Route as CSlugRoleplayIndexRouteImport } from './routes/c/$slug/roleplay/index'
import { Route as CSlugRoleplaySceneIdRouteImport } from './routes/c/$slug/roleplay/$sceneId'
import { Route as ApiV1MediaAvatarUserIdRouteImport } from './routes/api/v1/media/avatar/$userId'
import { Route as ApiV1MediaCoverUserIdRouteImport } from './routes/api/v1/media/cover/$userId'
import { Route as ApiV1MediaCommunitySlugKindRouteImport } from './routes/api/v1/media/community/$slug/$kind'
import { Route as ApiV1MediaMessageRoomIdMessageIdRouteImport } from './routes/api/v1/media/message/$roomId/$messageId'
import { Route as ApiV1MediaPostPostIdPositionRouteImport } from './routes/api/v1/media/post/$postId/$position'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaRoute = CaptchaRouteImport.update({
  id: '/captcha',
  path: '/captcha',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafetyRoute = ChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentStudioRoute = ContentStudioRouteImport.update({
  id: '/content-studio',
  path: '/content-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverPlusRoute = DiscoverPlusRouteImport.update({
  id: '/discover-plus',
  path: '/discover-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxToolsRoute = InboxToolsRouteImport.update({
  id: '/inbox-tools',
  path: '/inbox-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaLibraryRoute = MediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyDashboardRoute = PrivacyDashboardRouteImport.update({
  id: '/privacy-dashboard',
  path: '/privacy-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileStoriesRoute = ProfileStoriesRouteImport.update({
  id: '/profile-stories',
  path: '/profile-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortVideosRoute = ShortVideosRouteImport.update({
  id: '/short-videos',
  path: '/short-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSearchRoute = SmartSearchRouteImport.update({
  id: '/smart-search',
  path: '/smart-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRoute,
} as any)
const ChatsRoomIdRoute = ChatsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ChatsRoute,
} as any)
const GroupsRoomIdRoute = GroupsRoomIdRouteImport.update({
  id: '/groups/$roomId',
  path: '/groups/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JobsRoute = ApiV1JobsRouteImport.update({
  id: '/api/v1/jobs',
  path: '/api/v1/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugChatsRoute = CSlugChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugEventsRoute = CSlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugFilesRoute = CSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugMembersRoute = CSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugModRoute = CSlugModRouteImport.update({
  id: '/mod',
  path: '/mod',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugRankRoute = CSlugRankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugToolsRoute = CSlugToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugWikiRoute = CSlugWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => CSlugRoute,
} as any)
const ApiV1AuthMobileCallbackRoute = ApiV1AuthMobileCallbackRouteImport.update({
  id: '/api/v1/auth/mobile-callback',
  path: '/api/v1/auth/mobile-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMobileStartRoute = ApiV1AuthMobileStartRouteImport.update({
  id: '/api/v1/auth/mobile-start',
  path: '/api/v1/auth/mobile-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingStripeWebhookRoute =
  ApiV1BillingStripeWebhookRouteImport.update({
    id: '/api/v1/billing/stripe-webhook',
    path: '/api/v1/billing/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ContentMediaMediaIdRoute =
  ApiV1ContentMediaMediaIdRouteImport.update({
    id: '/api/v1/content-media/$mediaId',
    path: '/api/v1/content-media/$mediaId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1LibraryMediaLibraryIdRoute =
  ApiV1LibraryMediaLibraryIdRouteImport.update({
    id: '/api/v1/library-media/$libraryId',
    path: '/api/v1/library-media/$libraryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProfileStoryMediaStoryIdRoute =
  ApiV1ProfileStoryMediaStoryIdRouteImport.update({
    id: '/api/v1/profile-story-media/$storyId',
    path: '/api/v1/profile-story-media/$storyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1RpcNameRoute = ApiV1RpcNameRouteImport.update({
  id: '/api/v1/rpc/$name',
  path: '/api/v1/rpc/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugPPostIdRoute = CSlugPPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugRoleplayIndexRoute = CSlugRoleplayIndexRouteImport.update({
  id: '/roleplay/',
  path: '/roleplay/',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugRoleplaySceneIdRoute = CSlugRoleplaySceneIdRouteImport.update({
  id: '/roleplay/$sceneId',
  path: '/roleplay/$sceneId',
  getParentRoute: () => CSlugRoute,
} as any)
const ApiV1MediaAvatarUserIdRoute = ApiV1MediaAvatarUserIdRouteImport.update({
  id: '/api/v1/media/avatar/$userId',
  path: '/api/v1/media/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaCoverUserIdRoute = ApiV1MediaCoverUserIdRouteImport.update({
  id: '/api/v1/media/cover/$userId',
  path: '/api/v1/media/cover/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaCommunitySlugKindRoute =
  ApiV1MediaCommunitySlugKindRouteImport.update({
    id: '/api/v1/media/community/$slug/$kind',
    path: '/api/v1/media/community/$slug/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MediaMessageRoomIdMessageIdRoute =
  ApiV1MediaMessageRoomIdMessageIdRouteImport.update({
    id: '/api/v1/media/message/$roomId/$messageId',
    path: '/api/v1/media/message/$roomId/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MediaPostPostIdPositionRoute =
  ApiV1MediaPostPostIdPositionRouteImport.update({
    id: '/api/v1/media/post/$postId/$position',
    path: '/api/v1/media/post/$postId/$position',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/appeal': typeof AppealRoute
  '/captcha': typeof CaptchaRoute
  '/chats': typeof ChatsRouteWithChildren
  '/child-safety': typeof ChildSafetyRoute
  '/connections': typeof ConnectionsRoute
  '/content-studio': typeof ContentStudioRoute
  '/copyright': typeof CopyrightRoute
  '/creator': typeof CreatorRoute
  '/delete-account': typeof DeleteAccountRoute
  '/discover-plus': typeof DiscoverPlusRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox-tools': typeof InboxToolsRoute
  '/kit': typeof KitRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/me': typeof MeRoute
  '/media-library': typeof MediaLibraryRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-dashboard': typeof PrivacyDashboardRoute
  '/profile-stories': typeof ProfileStoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/short-videos': typeof ShortVideosRoute
  '/smart-search': typeof SmartSearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/groups/$roomId': typeof GroupsRoomIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/u/$handle': typeof UHandleRoute
  '/chats/': typeof ChatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/jobs': typeof ApiV1JobsRoute
  '/c/$slug/chats': typeof CSlugChatsRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/files': typeof CSlugFilesRoute
  '/c/$slug/members': typeof CSlugMembersRoute
  '/c/$slug/mod': typeof CSlugModRoute
  '/c/$slug/rank': typeof CSlugRankRoute
  '/c/$slug/tools': typeof CSlugToolsRoute
  '/c/$slug/wiki': typeof CSlugWikiRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/api/v1/auth/mobile-callback': typeof ApiV1AuthMobileCallbackRoute
  '/api/v1/auth/mobile-start': typeof ApiV1AuthMobileStartRoute
  '/api/v1/billing/stripe-webhook': typeof ApiV1BillingStripeWebhookRoute
  '/api/v1/content-media/$mediaId': typeof ApiV1ContentMediaMediaIdRoute
  '/api/v1/library-media/$libraryId': typeof ApiV1LibraryMediaLibraryIdRoute
  '/api/v1/profile-story-media/$storyId': typeof ApiV1ProfileStoryMediaStoryIdRoute
  '/api/v1/rpc/$name': typeof ApiV1RpcNameRoute
  '/c/$slug/p/$postId': typeof CSlugPPostIdRoute
  '/c/$slug/roleplay/$sceneId': typeof CSlugRoleplaySceneIdRoute
  '/c/$slug/roleplay/': typeof CSlugRoleplayIndexRoute
  '/api/v1/media/avatar/$userId': typeof ApiV1MediaAvatarUserIdRoute
  '/api/v1/media/cover/$userId': typeof ApiV1MediaCoverUserIdRoute
  '/api/v1/media/community/$slug/$kind': typeof ApiV1MediaCommunitySlugKindRoute
  '/api/v1/media/message/$roomId/$messageId': typeof ApiV1MediaMessageRoomIdMessageIdRoute
  '/api/v1/media/post/$postId/$position': typeof ApiV1MediaPostPostIdPositionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/appeal': typeof AppealRoute
  '/captcha': typeof CaptchaRoute
  '/child-safety': typeof ChildSafetyRoute
  '/connections': typeof ConnectionsRoute
  '/content-studio': typeof ContentStudioRoute
  '/copyright': typeof CopyrightRoute
  '/creator': typeof CreatorRoute
  '/delete-account': typeof DeleteAccountRoute
  '/discover-plus': typeof DiscoverPlusRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox-tools': typeof InboxToolsRoute
  '/kit': typeof KitRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/me': typeof MeRoute
  '/media-library': typeof MediaLibraryRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-dashboard': typeof PrivacyDashboardRoute
  '/profile-stories': typeof ProfileStoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/short-videos': typeof ShortVideosRoute
  '/smart-search': typeof SmartSearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/groups/$roomId': typeof GroupsRoomIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/u/$handle': typeof UHandleRoute
  '/chats': typeof ChatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/jobs': typeof ApiV1JobsRoute
  '/c/$slug/chats': typeof CSlugChatsRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/files': typeof CSlugFilesRoute
  '/c/$slug/members': typeof CSlugMembersRoute
  '/c/$slug/mod': typeof CSlugModRoute
  '/c/$slug/rank': typeof CSlugRankRoute
  '/c/$slug/tools': typeof CSlugToolsRoute
  '/c/$slug/wiki': typeof CSlugWikiRoute
  '/c/$slug': typeof CSlugIndexRoute
  '/api/v1/auth/mobile-callback': typeof ApiV1AuthMobileCallbackRoute
  '/api/v1/auth/mobile-start': typeof ApiV1AuthMobileStartRoute
  '/api/v1/billing/stripe-webhook': typeof ApiV1BillingStripeWebhookRoute
  '/api/v1/content-media/$mediaId': typeof ApiV1ContentMediaMediaIdRoute
  '/api/v1/library-media/$libraryId': typeof ApiV1LibraryMediaLibraryIdRoute
  '/api/v1/profile-story-media/$storyId': typeof ApiV1ProfileStoryMediaStoryIdRoute
  '/api/v1/rpc/$name': typeof ApiV1RpcNameRoute
  '/c/$slug/p/$postId': typeof CSlugPPostIdRoute
  '/c/$slug/roleplay/$sceneId': typeof CSlugRoleplaySceneIdRoute
  '/c/$slug/roleplay': typeof CSlugRoleplayIndexRoute
  '/api/v1/media/avatar/$userId': typeof ApiV1MediaAvatarUserIdRoute
  '/api/v1/media/cover/$userId': typeof ApiV1MediaCoverUserIdRoute
  '/api/v1/media/community/$slug/$kind': typeof ApiV1MediaCommunitySlugKindRoute
  '/api/v1/media/message/$roomId/$messageId': typeof ApiV1MediaMessageRoomIdMessageIdRoute
  '/api/v1/media/post/$postId/$position': typeof ApiV1MediaPostPostIdPositionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/appeal': typeof AppealRoute
  '/captcha': typeof CaptchaRoute
  '/chats': typeof ChatsRouteWithChildren
  '/child-safety': typeof ChildSafetyRoute
  '/connections': typeof ConnectionsRoute
  '/content-studio': typeof ContentStudioRoute
  '/copyright': typeof CopyrightRoute
  '/creator': typeof CreatorRoute
  '/delete-account': typeof DeleteAccountRoute
  '/discover-plus': typeof DiscoverPlusRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox-tools': typeof InboxToolsRoute
  '/kit': typeof KitRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/me': typeof MeRoute
  '/media-library': typeof MediaLibraryRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-dashboard': typeof PrivacyDashboardRoute
  '/profile-stories': typeof ProfileStoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/short-videos': typeof ShortVideosRoute
  '/smart-search': typeof SmartSearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/groups/$roomId': typeof GroupsRoomIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/u/$handle': typeof UHandleRoute
  '/chats/': typeof ChatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/jobs': typeof ApiV1JobsRoute
  '/c/$slug/chats': typeof CSlugChatsRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/files': typeof CSlugFilesRoute
  '/c/$slug/members': typeof CSlugMembersRoute
  '/c/$slug/mod': typeof CSlugModRoute
  '/c/$slug/rank': typeof CSlugRankRoute
  '/c/$slug/tools': typeof CSlugToolsRoute
  '/c/$slug/wiki': typeof CSlugWikiRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/api/v1/auth/mobile-callback': typeof ApiV1AuthMobileCallbackRoute
  '/api/v1/auth/mobile-start': typeof ApiV1AuthMobileStartRoute
  '/api/v1/billing/stripe-webhook': typeof ApiV1BillingStripeWebhookRoute
  '/api/v1/content-media/$mediaId': typeof ApiV1ContentMediaMediaIdRoute
  '/api/v1/library-media/$libraryId': typeof ApiV1LibraryMediaLibraryIdRoute
  '/api/v1/profile-story-media/$storyId': typeof ApiV1ProfileStoryMediaStoryIdRoute
  '/api/v1/rpc/$name': typeof ApiV1RpcNameRoute
  '/c/$slug/p/$postId': typeof CSlugPPostIdRoute
  '/c/$slug/roleplay/$sceneId': typeof CSlugRoleplaySceneIdRoute
  '/c/$slug/roleplay/': typeof CSlugRoleplayIndexRoute
  '/api/v1/media/avatar/$userId': typeof ApiV1MediaAvatarUserIdRoute
  '/api/v1/media/cover/$userId': typeof ApiV1MediaCoverUserIdRoute
  '/api/v1/media/community/$slug/$kind': typeof ApiV1MediaCommunitySlugKindRoute
  '/api/v1/media/message/$roomId/$messageId': typeof ApiV1MediaMessageRoomIdMessageIdRoute
  '/api/v1/media/post/$postId/$position': typeof ApiV1MediaPostPostIdPositionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-analytics'
    | '/appeal'
    | '/captcha'
    | '/chats'
    | '/child-safety'
    | '/connections'
    | '/content-studio'
    | '/copyright'
    | '/creator'
    | '/delete-account'
    | '/discover-plus'
    | '/explore'
    | '/forgot-password'
    | '/inbox-tools'
    | '/kit'
    | '/login'
    | '/marketplace'
    | '/me'
    | '/media-library'
    | '/new'
    | '/notifications'
    | '/onboarding'
    | '/operations'
    | '/privacy'
    | '/privacy-dashboard'
    | '/profile-stories'
    | '/reset-password'
    | '/safety'
    | '/saved'
    | '/security'
    | '/settings'
    | '/short-videos'
    | '/smart-search'
    | '/support'
    | '/terms'
    | '/tutorial'
    | '/welcome'
    | '/admin/operations'
    | '/admin/reports'
    | '/admin/safety'
    | '/api/rtc'
    | '/c/$slug'
    | '/chats/$roomId'
    | '/groups/$roomId'
    | '/invite/$code'
    | '/u/$handle'
    | '/chats/'
    | '/api/auth/$'
    | '/api/v1/jobs'
    | '/c/$slug/chats'
    | '/c/$slug/events'
    | '/c/$slug/files'
    | '/c/$slug/members'
    | '/c/$slug/mod'
    | '/c/$slug/rank'
    | '/c/$slug/tools'
    | '/c/$slug/wiki'
    | '/c/$slug/'
    | '/api/v1/auth/mobile-callback'
    | '/api/v1/auth/mobile-start'
    | '/api/v1/billing/stripe-webhook'
    | '/api/v1/content-media/$mediaId'
    | '/api/v1/library-media/$libraryId'
    | '/api/v1/profile-story-media/$storyId'
    | '/api/v1/rpc/$name'
    | '/c/$slug/p/$postId'
    | '/c/$slug/roleplay/$sceneId'
    | '/c/$slug/roleplay/'
    | '/api/v1/media/avatar/$userId'
    | '/api/v1/media/cover/$userId'
    | '/api/v1/media/community/$slug/$kind'
    | '/api/v1/media/message/$roomId/$messageId'
    | '/api/v1/media/post/$postId/$position'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-analytics'
    | '/appeal'
    | '/captcha'
    | '/child-safety'
    | '/connections'
    | '/content-studio'
    | '/copyright'
    | '/creator'
    | '/delete-account'
    | '/discover-plus'
    | '/explore'
    | '/forgot-password'
    | '/inbox-tools'
    | '/kit'
    | '/login'
    | '/marketplace'
    | '/me'
    | '/media-library'
    | '/new'
    | '/notifications'
    | '/onboarding'
    | '/operations'
    | '/privacy'
    | '/privacy-dashboard'
    | '/profile-stories'
    | '/reset-password'
    | '/safety'
    | '/saved'
    | '/security'
    | '/settings'
    | '/short-videos'
    | '/smart-search'
    | '/support'
    | '/terms'
    | '/tutorial'
    | '/welcome'
    | '/admin/operations'
    | '/admin/reports'
    | '/admin/safety'
    | '/api/rtc'
    | '/chats/$roomId'
    | '/groups/$roomId'
    | '/invite/$code'
    | '/u/$handle'
    | '/chats'
    | '/api/auth/$'
    | '/api/v1/jobs'
    | '/c/$slug/chats'
    | '/c/$slug/events'
    | '/c/$slug/files'
    | '/c/$slug/members'
    | '/c/$slug/mod'
    | '/c/$slug/rank'
    | '/c/$slug/tools'
    | '/c/$slug/wiki'
    | '/c/$slug'
    | '/api/v1/auth/mobile-callback'
    | '/api/v1/auth/mobile-start'
    | '/api/v1/billing/stripe-webhook'
    | '/api/v1/content-media/$mediaId'
    | '/api/v1/library-media/$libraryId'
    | '/api/v1/profile-story-media/$storyId'
    | '/api/v1/rpc/$name'
    | '/c/$slug/p/$postId'
    | '/c/$slug/roleplay/$sceneId'
    | '/c/$slug/roleplay'
    | '/api/v1/media/avatar/$userId'
    | '/api/v1/media/cover/$userId'
    | '/api/v1/media/community/$slug/$kind'
    | '/api/v1/media/message/$roomId/$messageId'
    | '/api/v1/media/post/$postId/$position'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-analytics'
    | '/appeal'
    | '/captcha'
    | '/chats'
    | '/child-safety'
    | '/connections'
    | '/content-studio'
    | '/copyright'
    | '/creator'
    | '/delete-account'
    | '/discover-plus'
    | '/explore'
    | '/forgot-password'
    | '/inbox-tools'
    | '/kit'
    | '/login'
    | '/marketplace'
    | '/me'
    | '/media-library'
    | '/new'
    | '/notifications'
    | '/onboarding'
    | '/operations'
    | '/privacy'
    | '/privacy-dashboard'
    | '/profile-stories'
    | '/reset-password'
    | '/safety'
    | '/saved'
    | '/security'
    | '/settings'
    | '/short-videos'
    | '/smart-search'
    | '/support'
    | '/terms'
    | '/tutorial'
    | '/welcome'
    | '/admin/operations'
    | '/admin/reports'
    | '/admin/safety'
    | '/api/rtc'
    | '/c/$slug'
    | '/chats/$roomId'
    | '/groups/$roomId'
    | '/invite/$code'
    | '/u/$handle'
    | '/chats/'
    | '/api/auth/$'
    | '/api/v1/jobs'
    | '/c/$slug/chats'
    | '/c/$slug/events'
    | '/c/$slug/files'
    | '/c/$slug/members'
    | '/c/$slug/mod'
    | '/c/$slug/rank'
    | '/c/$slug/tools'
    | '/c/$slug/wiki'
    | '/c/$slug/'
    | '/api/v1/auth/mobile-callback'
    | '/api/v1/auth/mobile-start'
    | '/api/v1/billing/stripe-webhook'
    | '/api/v1/content-media/$mediaId'
    | '/api/v1/library-media/$libraryId'
    | '/api/v1/profile-story-media/$storyId'
    | '/api/v1/rpc/$name'
    | '/c/$slug/p/$postId'
    | '/c/$slug/roleplay/$sceneId'
    | '/c/$slug/roleplay/'
    | '/api/v1/media/avatar/$userId'
    | '/api/v1/media/cover/$userId'
    | '/api/v1/media/community/$slug/$kind'
    | '/api/v1/media/message/$roomId/$messageId'
    | '/api/v1/media/post/$postId/$position'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AppealRoute: typeof AppealRoute
  CaptchaRoute: typeof CaptchaRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  ChildSafetyRoute: typeof ChildSafetyRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ContentStudioRoute: typeof ContentStudioRoute
  CopyrightRoute: typeof CopyrightRoute
  CreatorRoute: typeof CreatorRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DiscoverPlusRoute: typeof DiscoverPlusRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InboxToolsRoute: typeof InboxToolsRoute
  KitRoute: typeof KitRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MeRoute: typeof MeRoute
  MediaLibraryRoute: typeof MediaLibraryRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OperationsRoute: typeof OperationsRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyDashboardRoute: typeof PrivacyDashboardRoute
  ProfileStoriesRoute: typeof ProfileStoriesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  SavedRoute: typeof SavedRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  ShortVideosRoute: typeof ShortVideosRoute
  SmartSearchRoute: typeof SmartSearchRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TutorialRoute: typeof TutorialRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiRtcRoute: typeof ApiRtcRoute
  CSlugRoute: typeof CSlugRouteWithChildren
  GroupsRoomIdRoute: typeof GroupsRoomIdRoute
  InviteCodeRoute: typeof InviteCodeRoute
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1JobsRoute: typeof ApiV1JobsRoute
  ApiV1AuthMobileCallbackRoute: typeof ApiV1AuthMobileCallbackRoute
  ApiV1AuthMobileStartRoute: typeof ApiV1AuthMobileStartRoute
  ApiV1BillingStripeWebhookRoute: typeof ApiV1BillingStripeWebhookRoute
  ApiV1ContentMediaMediaIdRoute: typeof ApiV1ContentMediaMediaIdRoute
  ApiV1LibraryMediaLibraryIdRoute: typeof ApiV1LibraryMediaLibraryIdRoute
  ApiV1ProfileStoryMediaStoryIdRoute: typeof ApiV1ProfileStoryMediaStoryIdRoute
  ApiV1RpcNameRoute: typeof ApiV1RpcNameRoute
  ApiV1MediaAvatarUserIdRoute: typeof ApiV1MediaAvatarUserIdRoute
  ApiV1MediaCoverUserIdRoute: typeof ApiV1MediaCoverUserIdRoute
  ApiV1MediaCommunitySlugKindRoute: typeof ApiV1MediaCommunitySlugKindRoute
  ApiV1MediaMessageRoomIdMessageIdRoute: typeof ApiV1MediaMessageRoomIdMessageIdRoute
  ApiV1MediaPostPostIdPositionRoute: typeof ApiV1MediaPostPostIdPositionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-analytics': {
      id: '/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha': {
      id: '/captcha'
      path: '/captcha'
      fullPath: '/captcha'
      preLoaderRoute: typeof CaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-safety': {
      id: '/child-safety'
      path: '/child-safety'
      fullPath: '/child-safety'
      preLoaderRoute: typeof ChildSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-studio': {
      id: '/content-studio'
      path: '/content-studio'
      fullPath: '/content-studio'
      preLoaderRoute: typeof ContentStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover-plus': {
      id: '/discover-plus'
      path: '/discover-plus'
      fullPath: '/discover-plus'
      preLoaderRoute: typeof DiscoverPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-tools': {
      id: '/inbox-tools'
      path: '/inbox-tools'
      fullPath: '/inbox-tools'
      preLoaderRoute: typeof InboxToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-library': {
      id: '/media-library'
      path: '/media-library'
      fullPath: '/media-library'
      preLoaderRoute: typeof MediaLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-dashboard': {
      id: '/privacy-dashboard'
      path: '/privacy-dashboard'
      fullPath: '/privacy-dashboard'
      preLoaderRoute: typeof PrivacyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-stories': {
      id: '/profile-stories'
      path: '/profile-stories'
      fullPath: '/profile-stories'
      preLoaderRoute: typeof ProfileStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-videos': {
      id: '/short-videos'
      path: '/short-videos'
      fullPath: '/short-videos'
      preLoaderRoute: typeof ShortVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-search': {
      id: '/smart-search'
      path: '/smart-search'
      fullPath: '/smart-search'
      preLoaderRoute: typeof SmartSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/chats/$roomId': {
      id: '/chats/$roomId'
      path: '/$roomId'
      fullPath: '/chats/$roomId'
      preLoaderRoute: typeof ChatsRoomIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/groups/$roomId': {
      id: '/groups/$roomId'
      path: '/groups/$roomId'
      fullPath: '/groups/$roomId'
      preLoaderRoute: typeof GroupsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs': {
      id: '/api/v1/jobs'
      path: '/api/v1/jobs'
      fullPath: '/api/v1/jobs'
      preLoaderRoute: typeof ApiV1JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/chats': {
      id: '/c/$slug/chats'
      path: '/chats'
      fullPath: '/c/$slug/chats'
      preLoaderRoute: typeof CSlugChatsRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/events': {
      id: '/c/$slug/events'
      path: '/events'
      fullPath: '/c/$slug/events'
      preLoaderRoute: typeof CSlugEventsRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/files': {
      id: '/c/$slug/files'
      path: '/files'
      fullPath: '/c/$slug/files'
      preLoaderRoute: typeof CSlugFilesRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/members': {
      id: '/c/$slug/members'
      path: '/members'
      fullPath: '/c/$slug/members'
      preLoaderRoute: typeof CSlugMembersRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/mod': {
      id: '/c/$slug/mod'
      path: '/mod'
      fullPath: '/c/$slug/mod'
      preLoaderRoute: typeof CSlugModRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/rank': {
      id: '/c/$slug/rank'
      path: '/rank'
      fullPath: '/c/$slug/rank'
      preLoaderRoute: typeof CSlugRankRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/tools': {
      id: '/c/$slug/tools'
      path: '/tools'
      fullPath: '/c/$slug/tools'
      preLoaderRoute: typeof CSlugToolsRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/wiki': {
      id: '/c/$slug/wiki'
      path: '/wiki'
      fullPath: '/c/$slug/wiki'
      preLoaderRoute: typeof CSlugWikiRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/api/v1/auth/mobile-callback': {
      id: '/api/v1/auth/mobile-callback'
      path: '/api/v1/auth/mobile-callback'
      fullPath: '/api/v1/auth/mobile-callback'
      preLoaderRoute: typeof ApiV1AuthMobileCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/mobile-start': {
      id: '/api/v1/auth/mobile-start'
      path: '/api/v1/auth/mobile-start'
      fullPath: '/api/v1/auth/mobile-start'
      preLoaderRoute: typeof ApiV1AuthMobileStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/stripe-webhook': {
      id: '/api/v1/billing/stripe-webhook'
      path: '/api/v1/billing/stripe-webhook'
      fullPath: '/api/v1/billing/stripe-webhook'
      preLoaderRoute: typeof ApiV1BillingStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/content-media/$mediaId': {
      id: '/api/v1/content-media/$mediaId'
      path: '/api/v1/content-media/$mediaId'
      fullPath: '/api/v1/content-media/$mediaId'
      preLoaderRoute: typeof ApiV1ContentMediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/library-media/$libraryId': {
      id: '/api/v1/library-media/$libraryId'
      path: '/api/v1/library-media/$libraryId'
      fullPath: '/api/v1/library-media/$libraryId'
      preLoaderRoute: typeof ApiV1LibraryMediaLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile-story-media/$storyId': {
      id: '/api/v1/profile-story-media/$storyId'
      path: '/api/v1/profile-story-media/$storyId'
      fullPath: '/api/v1/profile-story-media/$storyId'
      preLoaderRoute: typeof ApiV1ProfileStoryMediaStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rpc/$name': {
      id: '/api/v1/rpc/$name'
      path: '/api/v1/rpc/$name'
      fullPath: '/api/v1/rpc/$name'
      preLoaderRoute: typeof ApiV1RpcNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/p/$postId': {
      id: '/c/$slug/p/$postId'
      path: '/p/$postId'
      fullPath: '/c/$slug/p/$postId'
      preLoaderRoute: typeof CSlugPPostIdRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/roleplay/': {
      id: '/c/$slug/roleplay/'
      path: '/roleplay'
      fullPath: '/c/$slug/roleplay/'
      preLoaderRoute: typeof CSlugRoleplayIndexRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/roleplay/$sceneId': {
      id: '/c/$slug/roleplay/$sceneId'
      path: '/roleplay/$sceneId'
      fullPath: '/c/$slug/roleplay/$sceneId'
      preLoaderRoute: typeof CSlugRoleplaySceneIdRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/api/v1/media/avatar/$userId': {
      id: '/api/v1/media/avatar/$userId'
      path: '/api/v1/media/avatar/$userId'
      fullPath: '/api/v1/media/avatar/$userId'
      preLoaderRoute: typeof ApiV1MediaAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/cover/$userId': {
      id: '/api/v1/media/cover/$userId'
      path: '/api/v1/media/cover/$userId'
      fullPath: '/api/v1/media/cover/$userId'
      preLoaderRoute: typeof ApiV1MediaCoverUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/community/$slug/$kind': {
      id: '/api/v1/media/community/$slug/$kind'
      path: '/api/v1/media/community/$slug/$kind'
      fullPath: '/api/v1/media/community/$slug/$kind'
      preLoaderRoute: typeof ApiV1MediaCommunitySlugKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/message/$roomId/$messageId': {
      id: '/api/v1/media/message/$roomId/$messageId'
      path: '/api/v1/media/message/$roomId/$messageId'
      fullPath: '/api/v1/media/message/$roomId/$messageId'
      preLoaderRoute: typeof ApiV1MediaMessageRoomIdMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/post/$postId/$position': {
      id: '/api/v1/media/post/$postId/$position'
      path: '/api/v1/media/post/$postId/$position'
      fullPath: '/api/v1/media/post/$postId/$position'
      preLoaderRoute: typeof ApiV1MediaPostPostIdPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSafetyRoute: typeof AdminSafetyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOperationsRoute: AdminOperationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSafetyRoute: AdminSafetyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChatsRouteChildren {
  ChatsRoomIdRoute: typeof ChatsRoomIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsRoomIdRoute: ChatsRoomIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface CSlugRouteChildren {
  CSlugChatsRoute: typeof CSlugChatsRoute
  CSlugEventsRoute: typeof CSlugEventsRoute
  CSlugFilesRoute: typeof CSlugFilesRoute
  CSlugMembersRoute: typeof CSlugMembersRoute
  CSlugModRoute: typeof CSlugModRoute
  CSlugRankRoute: typeof CSlugRankRoute
  CSlugToolsRoute: typeof CSlugToolsRoute
  CSlugWikiRoute: typeof CSlugWikiRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
  CSlugPPostIdRoute: typeof CSlugPPostIdRoute
  CSlugRoleplaySceneIdRoute: typeof CSlugRoleplaySceneIdRoute
  CSlugRoleplayIndexRoute: typeof CSlugRoleplayIndexRoute
}

const CSlugRouteChildren: CSlugRouteChildren = {
  CSlugChatsRoute: CSlugChatsRoute,
  CSlugEventsRoute: CSlugEventsRoute,
  CSlugFilesRoute: CSlugFilesRoute,
  CSlugMembersRoute: CSlugMembersRoute,
  CSlugModRoute: CSlugModRoute,
  CSlugRankRoute: CSlugRankRoute,
  CSlugToolsRoute: CSlugToolsRoute,
  CSlugWikiRoute: CSlugWikiRoute,
  CSlugIndexRoute: CSlugIndexRoute,
  CSlugPPostIdRoute: CSlugPPostIdRoute,
  CSlugRoleplaySceneIdRoute: CSlugRoleplaySceneIdRoute,
  CSlugRoleplayIndexRoute: CSlugRoleplayIndexRoute,
}

const CSlugRouteWithChildren = CSlugRoute._addFileChildren(CSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AppealRoute: AppealRoute,
  CaptchaRoute: CaptchaRoute,
  ChatsRoute: ChatsRouteWithChildren,
  ChildSafetyRoute: ChildSafetyRoute,
  ConnectionsRoute: ConnectionsRoute,
  ContentStudioRoute: ContentStudioRoute,
  CopyrightRoute: CopyrightRoute,
  CreatorRoute: CreatorRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DiscoverPlusRoute: DiscoverPlusRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InboxToolsRoute: InboxToolsRoute,
  KitRoute: KitRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MeRoute: MeRoute,
  MediaLibraryRoute: MediaLibraryRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OperationsRoute: OperationsRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyDashboardRoute: PrivacyDashboardRoute,
  ProfileStoriesRoute: ProfileStoriesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  SavedRoute: SavedRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  ShortVideosRoute: ShortVideosRoute,
  SmartSearchRoute: SmartSearchRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TutorialRoute: TutorialRoute,
  WelcomeRoute: WelcomeRoute,
  ApiRtcRoute: ApiRtcRoute,
  CSlugRoute: CSlugRouteWithChildren,
  GroupsRoomIdRoute: GroupsRoomIdRoute,
  InviteCodeRoute: InviteCodeRoute,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1JobsRoute: ApiV1JobsRoute,
  ApiV1AuthMobileCallbackRoute: ApiV1AuthMobileCallbackRoute,
  ApiV1AuthMobileStartRoute: ApiV1AuthMobileStartRoute,
  ApiV1BillingStripeWebhookRoute: ApiV1BillingStripeWebhookRoute,
  ApiV1ContentMediaMediaIdRoute: ApiV1ContentMediaMediaIdRoute,
  ApiV1LibraryMediaLibraryIdRoute: ApiV1LibraryMediaLibraryIdRoute,
  ApiV1ProfileStoryMediaStoryIdRoute: ApiV1ProfileStoryMediaStoryIdRoute,
  ApiV1RpcNameRoute: ApiV1RpcNameRoute,
  ApiV1MediaAvatarUserIdRoute: ApiV1MediaAvatarUserIdRoute,
  ApiV1MediaCoverUserIdRoute: ApiV1MediaCoverUserIdRoute,
  ApiV1MediaCommunitySlugKindRoute: ApiV1MediaCommunitySlugKindRoute,
  ApiV1MediaMessageRoomIdMessageIdRoute: ApiV1MediaMessageRoomIdMessageIdRoute,
  ApiV1MediaPostPostIdPositionRoute: ApiV1MediaPostPostIdPositionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
