/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as NewRouteImport } from './routes/new'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as CSlugRouteImport } from './routes/c/$slug'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as ChatsRoomIdRouteImport } from './routes/chats/$roomId'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CSlugIndexRouteImport } from './routes/c/$slug/index'
import { Route as CSlugChatsRouteImport } from './routes/c/$slug/chats'
import { Route as CSlugEventsRouteImport } from './routes/c/$slug/events'
import { Route as CSlugFilesRouteImport } from './routes/c/$slug/files'
import { Route as CSlugMembersRouteImport } from './routes/c/$slug/members'
import { Route as CSlugModRouteImport } from './routes/c/$slug/mod'
import { Route as CSlugRankRouteImport } from './routes/c/$slug/rank'
import { Route as CSlugWikiRouteImport } from './routes/c/$slug/wiki'
import { Route as ApiV1RpcNameRouteImport } from './routes/api/v1/rpc/$name'
import { Route as CSlugPPostIdRouteImport } from './routes/c/$slug/p/$postId'
import { Route as ApiV1MediaAvatarUserIdRouteImport } from './routes/api/v1/media/avatar/$userId'
import { Route as ApiV1MediaCommunitySlugKindRouteImport } from './routes/api/v1/media/community/$slug/$kind'
import { Route as ApiV1MediaMessageRoomIdMessageIdRouteImport } from './routes/api/v1/media/message/$roomId/$messageId'
import { Route as ApiV1MediaPostPostIdPositionRouteImport } from './routes/api/v1/media/post/$postId/$position'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRoute,
} as any)
const ChatsRoomIdRoute = ChatsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ChatsRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugChatsRoute = CSlugChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugEventsRoute = CSlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugFilesRoute = CSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugMembersRoute = CSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugModRoute = CSlugModRouteImport.update({
  id: '/mod',
  path: '/mod',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugRankRoute = CSlugRankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugWikiRoute = CSlugWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => CSlugRoute,
} as any)
const ApiV1RpcNameRoute = ApiV1RpcNameRouteImport.update({
  id: '/api/v1/rpc/$name',
  path: '/api/v1/rpc/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugPPostIdRoute = CSlugPPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => CSlugRoute,
} as any)
const ApiV1MediaAvatarUserIdRoute = ApiV1MediaAvatarUserIdRouteImport.update({
  id: '/api/v1/media/avatar/$userId',
  path: '/api/v1/media/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaCommunitySlugKindRoute =
  ApiV1MediaCommunitySlugKindRouteImport.update({
    id: '/api/v1/media/community/$slug/$kind',
    path: '/api/v1/media/community/$slug/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MediaMessageRoomIdMessageIdRoute =
  ApiV1MediaMessageRoomIdMessageIdRouteImport.update({
    id: '/api/v1/media/message/$roomId/$messageId',
    path: '/api/v1/media/message/$roomId/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MediaPostPostIdPositionRoute =
  ApiV1MediaPostPostIdPositionRouteImport.update({
    id: '/api/v1/media/post/$postId/$position',
    path: '/api/v1/media/post/$postId/$position',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/api/rtc': typeof ApiRtcRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/u/$handle': typeof UHandleRoute
  '/chats/': typeof ChatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$slug/chats': typeof CSlugChatsRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/files': typeof CSlugFilesRoute
  '/c/$slug/members': typeof CSlugMembersRoute
  '/c/$slug/mod': typeof CSlugModRoute
  '/c/$slug/rank': typeof CSlugRankRoute
  '/c/$slug/wiki': typeof CSlugWikiRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/api/v1/rpc/$name': typeof ApiV1RpcNameRoute
  '/c/$slug/p/$postId': typeof CSlugPPostIdRoute
  '/api/v1/media/avatar/$userId': typeof ApiV1MediaAvatarUserIdRoute
  '/api/v1/media/community/$slug/$kind': typeof ApiV1MediaCommunitySlugKindRoute
  '/api/v1/media/message/$roomId/$messageId': typeof ApiV1MediaMessageRoomIdMessageIdRoute
  '/api/v1/media/post/$postId/$position': typeof ApiV1MediaPostPostIdPositionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/api/rtc': typeof ApiRtcRoute
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/u/$handle': typeof UHandleRoute
  '/chats': typeof ChatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$slug/chats': typeof CSlugChatsRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/files': typeof CSlugFilesRoute
  '/c/$slug/members': typeof CSlugMembersRoute
  '/c/$slug/mod': typeof CSlugModRoute
  '/c/$slug/rank': typeof CSlugRankRoute
  '/c/$slug/wiki': typeof CSlugWikiRoute
  '/c/$slug': typeof CSlugIndexRoute
  '/api/v1/rpc/$name': typeof ApiV1RpcNameRoute
  '/c/$slug/p/$postId': typeof CSlugPPostIdRoute
  '/api/v1/media/avatar/$userId': typeof ApiV1MediaAvatarUserIdRoute
  '/api/v1/media/community/$slug/$kind': typeof ApiV1MediaCommunitySlugKindRoute
  '/api/v1/media/message/$roomId/$messageId': typeof ApiV1MediaMessageRoomIdMessageIdRoute
  '/api/v1/media/post/$postId/$position': typeof ApiV1MediaPostPostIdPositionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/api/rtc': typeof ApiRtcRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/u/$handle': typeof UHandleRoute
  '/chats/': typeof ChatsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$slug/chats': typeof CSlugChatsRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/files': typeof CSlugFilesRoute
  '/c/$slug/members': typeof CSlugMembersRoute
  '/c/$slug/mod': typeof CSlugModRoute
  '/c/$slug/rank': typeof CSlugRankRoute
  '/c/$slug/wiki': typeof CSlugWikiRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/api/v1/rpc/$name': typeof ApiV1RpcNameRoute
  '/c/$slug/p/$postId': typeof CSlugPPostIdRoute
  '/api/v1/media/avatar/$userId': typeof ApiV1MediaAvatarUserIdRoute
  '/api/v1/media/community/$slug/$kind': typeof ApiV1MediaCommunitySlugKindRoute
  '/api/v1/media/message/$roomId/$messageId': typeof ApiV1MediaMessageRoomIdMessageIdRoute
  '/api/v1/media/post/$postId/$position': typeof ApiV1MediaPostPostIdPositionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/delete-account'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/new'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/api/rtc'
    | '/c/$slug'
    | '/chats/$roomId'
    | '/u/$handle'
    | '/chats/'
    | '/api/auth/$'
    | '/c/$slug/chats'
    | '/c/$slug/events'
    | '/c/$slug/files'
    | '/c/$slug/members'
    | '/c/$slug/mod'
    | '/c/$slug/rank'
    | '/c/$slug/wiki'
    | '/c/$slug/'
    | '/api/v1/rpc/$name'
    | '/c/$slug/p/$postId'
    | '/api/v1/media/avatar/$userId'
    | '/api/v1/media/community/$slug/$kind'
    | '/api/v1/media/message/$roomId/$messageId'
    | '/api/v1/media/post/$postId/$position'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delete-account'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/new'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/api/rtc'
    | '/chats/$roomId'
    | '/u/$handle'
    | '/chats'
    | '/api/auth/$'
    | '/c/$slug/chats'
    | '/c/$slug/events'
    | '/c/$slug/files'
    | '/c/$slug/members'
    | '/c/$slug/mod'
    | '/c/$slug/rank'
    | '/c/$slug/wiki'
    | '/c/$slug'
    | '/api/v1/rpc/$name'
    | '/c/$slug/p/$postId'
    | '/api/v1/media/avatar/$userId'
    | '/api/v1/media/community/$slug/$kind'
    | '/api/v1/media/message/$roomId/$messageId'
    | '/api/v1/media/post/$postId/$position'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/delete-account'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/new'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/api/rtc'
    | '/c/$slug'
    | '/chats/$roomId'
    | '/u/$handle'
    | '/chats/'
    | '/api/auth/$'
    | '/c/$slug/chats'
    | '/c/$slug/events'
    | '/c/$slug/files'
    | '/c/$slug/members'
    | '/c/$slug/mod'
    | '/c/$slug/rank'
    | '/c/$slug/wiki'
    | '/c/$slug/'
    | '/api/v1/rpc/$name'
    | '/c/$slug/p/$postId'
    | '/api/v1/media/avatar/$userId'
    | '/api/v1/media/community/$slug/$kind'
    | '/api/v1/media/message/$roomId/$messageId'
    | '/api/v1/media/post/$postId/$position'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  ApiRtcRoute: typeof ApiRtcRoute
  CSlugRoute: typeof CSlugRouteWithChildren
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1RpcNameRoute: typeof ApiV1RpcNameRoute
  ApiV1MediaAvatarUserIdRoute: typeof ApiV1MediaAvatarUserIdRoute
  ApiV1MediaCommunitySlugKindRoute: typeof ApiV1MediaCommunitySlugKindRoute
  ApiV1MediaMessageRoomIdMessageIdRoute: typeof ApiV1MediaMessageRoomIdMessageIdRoute
  ApiV1MediaPostPostIdPositionRoute: typeof ApiV1MediaPostPostIdPositionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/chats/$roomId': {
      id: '/chats/$roomId'
      path: '/$roomId'
      fullPath: '/chats/$roomId'
      preLoaderRoute: typeof ChatsRoomIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/chats': {
      id: '/c/$slug/chats'
      path: '/chats'
      fullPath: '/c/$slug/chats'
      preLoaderRoute: typeof CSlugChatsRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/events': {
      id: '/c/$slug/events'
      path: '/events'
      fullPath: '/c/$slug/events'
      preLoaderRoute: typeof CSlugEventsRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/files': {
      id: '/c/$slug/files'
      path: '/files'
      fullPath: '/c/$slug/files'
      preLoaderRoute: typeof CSlugFilesRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/members': {
      id: '/c/$slug/members'
      path: '/members'
      fullPath: '/c/$slug/members'
      preLoaderRoute: typeof CSlugMembersRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/mod': {
      id: '/c/$slug/mod'
      path: '/mod'
      fullPath: '/c/$slug/mod'
      preLoaderRoute: typeof CSlugModRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/rank': {
      id: '/c/$slug/rank'
      path: '/rank'
      fullPath: '/c/$slug/rank'
      preLoaderRoute: typeof CSlugRankRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/wiki': {
      id: '/c/$slug/wiki'
      path: '/wiki'
      fullPath: '/c/$slug/wiki'
      preLoaderRoute: typeof CSlugWikiRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/api/v1/rpc/$name': {
      id: '/api/v1/rpc/$name'
      path: '/api/v1/rpc/$name'
      fullPath: '/api/v1/rpc/$name'
      preLoaderRoute: typeof ApiV1RpcNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/p/$postId': {
      id: '/c/$slug/p/$postId'
      path: '/p/$postId'
      fullPath: '/c/$slug/p/$postId'
      preLoaderRoute: typeof CSlugPPostIdRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/api/v1/media/avatar/$userId': {
      id: '/api/v1/media/avatar/$userId'
      path: '/api/v1/media/avatar/$userId'
      fullPath: '/api/v1/media/avatar/$userId'
      preLoaderRoute: typeof ApiV1MediaAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/community/$slug/$kind': {
      id: '/api/v1/media/community/$slug/$kind'
      path: '/api/v1/media/community/$slug/$kind'
      fullPath: '/api/v1/media/community/$slug/$kind'
      preLoaderRoute: typeof ApiV1MediaCommunitySlugKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/message/$roomId/$messageId': {
      id: '/api/v1/media/message/$roomId/$messageId'
      path: '/api/v1/media/message/$roomId/$messageId'
      fullPath: '/api/v1/media/message/$roomId/$messageId'
      preLoaderRoute: typeof ApiV1MediaMessageRoomIdMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/post/$postId/$position': {
      id: '/api/v1/media/post/$postId/$position'
      path: '/api/v1/media/post/$postId/$position'
      fullPath: '/api/v1/media/post/$postId/$position'
      preLoaderRoute: typeof ApiV1MediaPostPostIdPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatsRouteChildren {
  ChatsRoomIdRoute: typeof ChatsRoomIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsRoomIdRoute: ChatsRoomIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface CSlugRouteChildren {
  CSlugChatsRoute: typeof CSlugChatsRoute
  CSlugEventsRoute: typeof CSlugEventsRoute
  CSlugFilesRoute: typeof CSlugFilesRoute
  CSlugMembersRoute: typeof CSlugMembersRoute
  CSlugModRoute: typeof CSlugModRoute
  CSlugRankRoute: typeof CSlugRankRoute
  CSlugWikiRoute: typeof CSlugWikiRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
  CSlugPPostIdRoute: typeof CSlugPPostIdRoute
}

const CSlugRouteChildren: CSlugRouteChildren = {
  CSlugChatsRoute: CSlugChatsRoute,
  CSlugEventsRoute: CSlugEventsRoute,
  CSlugFilesRoute: CSlugFilesRoute,
  CSlugMembersRoute: CSlugMembersRoute,
  CSlugModRoute: CSlugModRoute,
  CSlugRankRoute: CSlugRankRoute,
  CSlugWikiRoute: CSlugWikiRoute,
  CSlugIndexRoute: CSlugIndexRoute,
  CSlugPPostIdRoute: CSlugPPostIdRoute,
}

const CSlugRouteWithChildren = CSlugRoute._addFileChildren(CSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  ApiRtcRoute: ApiRtcRoute,
  CSlugRoute: CSlugRouteWithChildren,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1RpcNameRoute: ApiV1RpcNameRoute,
  ApiV1MediaAvatarUserIdRoute: ApiV1MediaAvatarUserIdRoute,
  ApiV1MediaCommunitySlugKindRoute: ApiV1MediaCommunitySlugKindRoute,
  ApiV1MediaMessageRoomIdMessageIdRoute: ApiV1MediaMessageRoomIdMessageIdRoute,
  ApiV1MediaPostPostIdPositionRoute: ApiV1MediaPostPostIdPositionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
