import { useQuery } from '@tanstack/react-query';
import { useLocalSearchParams,router } from 'expo-router';
import { useState } from 'react';
import { Alert,Share,ScrollView,View } from 'react-native';
import { communityV9,type CommunityToolData,type CommunityPermission,type Policy,type Cosmetic } from '@/api/community-v9';
import { api } from '@/api/endpoints';
import { apiBaseUrl } from '@/api/config';
import { Button,Card,Chip,ErrorState,Field,Loading,Screen,Txt } from '@/components/ui';
import { withCommunityTheme } from '@/components/CommunityTheme';
import { showError } from '@/lib/errors';
import { parseLocalDateTime } from '@/lib/format';
import { space } from '@/theme';
type Act=(fn:()=>Promise<unknown>,message?:string)=>Promise<boolean>;
const permissionLabels:Record<CommunityPermission,string>={post:'Create posts',events:'Create events',live:'Start live rooms',invite:'Invite members',manage_faq:'Edit FAQs',manage_boards:'Manage boards',trusted:'Trusted member'};
function Tools(){
  const {slug}=useLocalSearchParams<{slug:string}>();const q=useQuery({queryKey:['community-tools',slug],queryFn:()=>communityV9.tools(slug!),enabled:!!slug});
  const [tab,setTab]=useState('faq'),[busy,setBusy]=useState(false);
  const act:Act=async(fn,message='Saved')=>{setBusy(true);try{await fn();await q.refetch();if(message)Alert.alert(message);return true;}catch(e){showError(e);return false;}finally{setBusy(false);}};
  if(q.isPending)return <Loading/>;if(q.error||!q.data)return <ErrorState error={q.error} onRetry={()=>void q.refetch()}/>;
  const data=q.data,member=data.member?.status==='active',lead=member&&['agent','leader'].includes(data.member!.role);
  const tabs=[['faq','FAQs'],['boards','Discussion boards'],...(member?[['quests','Quests & rewards']]:[]),...(data.isModerator?[['manage','Leader tools'],['analytics','Analytics']]:[])];
  return <Screen refreshing={q.isRefetching} onRefresh={()=>void q.refetch()}><Txt variant="heading">Community space</Txt><Txt tone="muted">Level {data.level} · {data.reputation.toLocaleString()} community reputation</Txt><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:space.sm}}>{tabs.map(([id,label])=><Chip key={id} label={label!} selected={tab===id} onPress={()=>setTab(id!)}/>)}</ScrollView>
    {tab==='faq'?<Faqs slug={slug!} data={data} act={act} busy={busy}/>:null}{tab==='boards'?<Boards slug={slug!} data={data} act={act} busy={busy}/>:null}{tab==='quests'?<Quests slug={slug!} lead={lead} act={act} busy={busy}/>:null}{tab==='analytics'&&data.isModerator?<Analytics slug={slug!}/>:null}{tab==='manage'&&data.isModerator?<Manage slug={slug!} data={data} lead={lead} act={act} busy={busy}/>:null}
    {data.badges.length?<Card><Txt variant="heading">Community achievements</Txt>{data.badges.map(b=><View key={b.id}><Txt>🏅 {b.badge} · {b.nickname}</Txt><Txt variant="small" tone="muted">{b.note}</Txt></View>)}</Card>:null}{member?<InvitePerson slug={slug!} act={act} busy={busy}/>:null}<Report slug={slug!} act={act} busy={busy}/>
  </Screen>;
}
function Faqs({slug,data,act,busy}:{slug:string;data:CommunityToolData;act:Act;busy:boolean}){
  const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[editing,setEditing]=useState<number|undefined>();const canEdit=data.permissions.includes('manage_faq');
  return <View style={{gap:space.md}}>{data.faqs.length?data.faqs.map(f=><Card key={f.id}><Txt variant="heading">{f.question}</Txt><Txt tone="muted">{f.answer}</Txt>{canEdit?<View style={{flexDirection:'row',gap:space.sm}}><Button small variant="secondary" label="Edit" onPress={()=>{setEditing(f.id);setQuestion(f.question);setAnswer(f.answer);}}/><Button small variant="danger" busy={busy} label="Remove" onPress={()=>void act(()=>communityV9.deleteFaq(slug,f.id),'FAQ removed')}/></View>:null}</Card>):<Txt tone="muted">Answers will appear here as the community grows.</Txt>}{canEdit?<Card><Txt variant="heading">{editing?'Edit answer':'Add an answer'}</Txt><Field label="Question" value={question} onChangeText={setQuestion} maxLength={200}/><Field label="Answer" value={answer} onChangeText={setAnswer} maxLength={4000} multiline/><Button busy={busy} label="Publish FAQ" onPress={()=>void act(()=>communityV9.saveFaq({slug,id:editing,question,answer}),'FAQ saved').then(ok=>{if(ok){setQuestion('');setAnswer('');setEditing(undefined);}})}/></Card>:null}</View>;
}
function Boards({slug,data,act,busy}:{slug:string;data:CommunityToolData;act:Act;busy:boolean}){
  const [selected,setSelected]=useState<number|null>(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[postId,setPostId]=useState<number|null>(null);
  const q=useQuery({queryKey:['board',slug,selected],queryFn:()=>communityV9.boardThreads(slug,selected!),enabled:selected!==null});const posts=useQuery({queryKey:['board-posts',slug],queryFn:()=>communityV9.boardPosts(slug),enabled:data.member?.status==='active'});
  return <View style={{gap:space.md}}>{data.boards.map(b=><Card key={b.id} onPress={()=>setSelected(b.id)}><Txt variant="heading">{b.name}</Txt><Txt tone="muted">{b.description}</Txt><Txt variant="caption" tone="subtle">{b.threadCount} discussions</Txt></Card>)}{!data.boards.length?<Txt tone="muted">A place for each conversation. Leaders can create boards here.</Txt>:null}{selected?<Card><Txt variant="heading">{q.data?.board.name??'Discussions'}</Txt>{q.error?<Txt tone="danger">{q.error.message}</Txt>:null}{q.data?.threads.map(p=><Card key={p.id} onPress={()=>router.push(`/community/${slug}/post/${p.id}`)}><Txt>{p.title}</Txt><Txt variant="small" tone="muted">{p.excerpt}</Txt><Txt variant="caption" tone="subtle">{p.nickname} · {p.comments} comments</Txt></Card>)}{q.data?.threads.length===0?<Txt tone="muted">No discussions yet.</Txt>:null}{posts.data?.length?<><Txt variant="label">Add an existing post</Txt><ScrollView horizontal contentContainerStyle={{gap:space.sm}}>{posts.data.map(p=><Chip key={p.id} label={p.title} selected={postId===p.id} onPress={()=>setPostId(p.id)}/>)}</ScrollView><Button small busy={busy} disabled={!postId} label="Add to board" onPress={()=>void act(async()=>{await communityV9.assignPost(slug,selected,postId!);await q.refetch();},'Discussion added')}/></>:<Button small variant="secondary" label="Create a discussion" onPress={()=>router.push({pathname:'/create',params:{slug}})}/>} {data.permissions.includes('manage_boards')?<Button small variant="danger" busy={busy} label="Remove board" onPress={()=>void act(()=>communityV9.deleteBoard(slug,selected),'Board removed').then(ok=>{if(ok)setSelected(null);})}/>:null}</Card>:null}{data.permissions.includes('manage_boards')?<Card><Txt variant="heading">New discussion board</Txt><Field label="Name" value={name} onChangeText={setName} maxLength={60}/><Field label="What belongs here" value={description} onChangeText={setDescription} maxLength={500} multiline/><Button busy={busy} label="Create board" onPress={()=>void act(()=>communityV9.saveBoard({slug,name,description}),'Board created').then(ok=>{if(ok){setName('');setDescription('');}})}/></Card>:null}</View>;
}
function Quests({slug,lead,act,busy}:{slug:string;lead:boolean;act:Act;busy:boolean}){
  const q=useQuery({queryKey:['quests',slug],queryFn:()=>communityV9.quests(slug)}),cosmetics=useQuery({queryKey:['earned-cosmetics'],queryFn:communityV9.cosmetics});
  const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[kind,setKind]=useState<'quest'|'weekly'|'seasonal'|'milestone'>('quest'),[metric,setMetric]=useState<'posts'|'comments'|'likes_received'|'checkins'>('posts'),[target,setTarget]=useState('5'),[badge,setBadge]=useState(''),[cosmetic,setCosmetic]=useState<''|Cosmetic>(''),[ends,setEnds]=useState('');
  return <View style={{gap:space.md}}><Txt variant="small" tone="muted">Goals count actual participation during the quest. Earn each reward once.</Txt>{q.data?.map(quest=><Card key={quest.id}><Chip label={quest.kind}/><Txt variant="heading">{quest.title}</Txt><Txt tone="muted">{quest.description}</Txt><Txt>{quest.progress}/{quest.target} {quest.metric.replace('_',' ')} · 🏅 {quest.badge}</Txt><Txt variant="caption" tone="subtle">{new Date(quest.startsAt).toLocaleDateString()}{quest.endsAt?` – ${new Date(quest.endsAt).toLocaleDateString()}`:''}{quest.rewardCosmetic?` · ${quest.rewardCosmetic} colour`:''}</Txt><Button small busy={busy} label={quest.claimedAt?'Reward earned':'Claim reward'} disabled={!!quest.claimedAt||quest.progress<quest.target||new Date(quest.startsAt)>new Date()} onPress={()=>void act(async()=>{await communityV9.claimQuest(slug,quest.id);await q.refetch();await cosmetics.refetch();},'Reward earned')}/></Card>)}{q.data?.length===0?<Txt tone="muted">No quests yet.</Txt>:null}{cosmetics.data?.length?<Card><Txt variant="heading">Earned chat colours</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{cosmetics.data.map(c=><Chip key={c.cosmetic} label={c.cosmetic} onPress={()=>void act(()=>communityV9.equipCosmetic(c.cosmetic),'Chat colour equipped')}/>)}</View></Card>:null}
    {lead?<Card><Txt variant="heading">Set a community goal</Txt><Field label="Title" value={title} onChangeText={setTitle} maxLength={100}/><Field label="Details" value={description} onChangeText={setDescription} multiline maxLength={1000}/><Txt variant="label">Type</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(['quest','weekly','seasonal','milestone'] as const).map(v=><Chip key={v} label={v} selected={kind===v} onPress={()=>setKind(v)}/>)}</View><Txt variant="label">Count</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(['posts','comments','likes_received','checkins'] as const).map(v=><Chip key={v} label={v.replace('_',' ')} selected={metric===v} onPress={()=>setMetric(v)}/>)}</View><Field label="Goal" value={target} onChangeText={setTarget} keyboardType="number-pad"/><Field label="Badge name" value={badge} onChangeText={setBadge} maxLength={60}/><Field label="Ends (optional, your local time)" value={ends} onChangeText={setEnds} placeholder="2026-12-31 21:00"/><Txt variant="label">Colour reward</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(['','aurora','sunrise','ocean','forest'] as const).map(v=><Chip key={v} label={v||'Badge only'} selected={cosmetic===v} onPress={()=>setCosmetic(v)}/>)}</View><Button busy={busy} label="Publish goal" onPress={()=>void act(async()=>{const end=ends?parseLocalDateTime(ends):kind==='weekly'?new Date(Date.now()+7*86400000).toISOString():undefined;if(ends&&!end)throw new Error('Write the end like 2026-12-31 21:00.');await communityV9.saveQuest({slug,title,description,kind,metric,target:Number(target),badge,rewardCosmetic:cosmetic,startsAt:new Date().toISOString(),endsAt:end??undefined});await q.refetch();},'Quest published').then(ok=>{if(ok){setTitle('');setDescription('');setBadge('');}})}/></Card>:null}
  </View>;
}
function Analytics({slug}:{slug:string}){const q=useQuery({queryKey:['community-analytics',slug],queryFn:()=>communityV9.analytics(slug)});if(q.isPending)return <Loading/>;if(q.error||!q.data)return <ErrorState error={q.error} onRetry={()=>void q.refetch()}/>;const d=q.data;return <View style={{gap:space.md}}><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{[['Members',d.members],['Joined in 30 days',d.newMembers30],['Daily active',d.dailyActive],['Weekly active',d.weeklyActive],['Monthly active',d.monthlyActive],['Retention',d.retentionPercent===null?'No history':`${d.retentionPercent}%`]].map(([label,value])=><Card key={label} style={{width:'48%'}}><Txt variant="caption" tone="muted">{label}</Txt><Txt variant="heading">{value}</Txt></Card>)}</View><Txt variant="caption" tone="muted">{d.definition}</Txt><Card><Txt variant="heading">Member growth</Txt>{d.growth.length?d.growth.map(g=><Txt key={g.day} variant="small">{g.day} · {g.count} joined</Txt>):<Txt tone="muted">No joins in the last 30 days.</Txt>}</Card><Card><Txt variant="heading">Top content · 30 days</Txt>{d.topContent.map(p=><Card key={p.id} onPress={()=>router.push(`/community/${slug}/post/${p.id}`)}><Txt>{p.title}</Txt><Txt variant="caption" tone="muted">{p.nickname} · {p.likes} likes · {p.comments} comments</Txt></Card>)}</Card></View>;}
function Manage({slug,data,lead,act,busy}:{slug:string;data:CommunityToolData;lead:boolean;act:Act;busy:boolean}){
  const [localArea,setLocalArea]=useState(data.settings.localArea),[memberLimit,setMemberLimit]=useState(data.settings.memberLimit?String(data.settings.memberLimit):''),[language,setLanguage]=useState(data.settings.language),[join,setJoin]=useState(data.settings.joinPolicy as 'open'|'approval'|'invite'),[post,setPost]=useState(data.settings.postPolicy as Policy),[live,setLive]=useState(data.settings.livePolicy as Policy),[event,setEvent]=useState(data.settings.eventPolicy as Policy),[keywords,setKeywords]=useState(data.settings.keywordFilters.join('\n'));
  const [label,setLabel]=useState(''),[permissions,setPermissions]=useState<CommunityPermission[]>([]),[selected,setSelected]=useState(''),[reason,setReason]=useState(''),[note,setNote]=useState(''),[badge,setBadge]=useState<'Helpful member'|'Kindness'|'Community star'>('Helpful member');
  const people=useQuery({queryKey:['mod-details',slug],queryFn:()=>communityV9.modDetails(slug)});
  return <View style={{gap:space.md}}><Button variant="secondary" label="Reports, bans & appeals" onPress={()=>router.push(`/community/${slug}/mod`)}/>{lead?<Card><Txt variant="heading">Community permissions</Txt><Txt variant="label">Language</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{[['en','English'],['es','Español'],['fr','Français'],['hi','हिन्दी'],['ja','日本語'],['ko','한국어'],['zh','中文'],['pt','Português'],['de','Deutsch']].map(([id,name])=><Chip key={id} label={name!} selected={language===id} onPress={()=>setLanguage(id!)}/>)}</View><Field label="Local area (optional)" value={localArea} onChangeText={setLocalArea} maxLength={150} placeholder="City or region"/><Field label="Micro-community member limit (10–50, optional)" value={memberLimit} onChangeText={setMemberLimit} keyboardType="number-pad" placeholder="Leave blank for no limit"/><Txt variant="label">Joining</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(['open','approval','invite'] as const).map(v=><Chip key={v} label={v==='invite'?'Invite only':v==='approval'?'Leader approval':'Open'} selected={join===v} onPress={()=>setJoin(v)}/>)}</View>{[['Posting',post,setPost],['Starting live rooms',live,setLive],['Creating events',event,setEvent]].map(([name,value,setter])=><View key={name as string} style={{gap:space.sm}}><Txt variant="label">{name as string}</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(['members','trusted','moderators'] as const).map(v=><Chip key={v} label={v} selected={value===v} onPress={()=>{(setter as (v:Policy)=>void)(v);}}/>)}</View></View>)}<Field label="Blocked phrases, one per line" value={keywords} onChangeText={setKeywords} multiline maxLength={8000}/><Button busy={busy} label="Save permissions" onPress={()=>void act(()=>communityV9.policies({slug,language,localArea,memberLimit:memberLimit.trim()?Number(memberLimit):null,joinPolicy:join,postPolicy:post,livePolicy:live,eventPolicy:event,keywordFilters:keywords.split('\n').map(x=>x.trim()).filter(Boolean)}))}/></Card>:null}
    {lead?<Card><Txt variant="heading">Invite link</Txt><Button small busy={busy} label="Create and share link" onPress={()=>void act(async()=>{const {code}=await api.createInvite(slug);await Share.share({message:`Join ${data.community.name} on Kamino: ${apiBaseUrl()}/invite/${code}`});},'')}/></Card>:null}
    {lead?<Card><Txt variant="heading">Custom community role</Txt><Field label="Role name" value={label} onChangeText={setLabel} maxLength={40} placeholder="Trusted member, Expert, Creator…"/><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(Object.keys(permissionLabels) as CommunityPermission[]).map(p=><Chip key={p} label={permissionLabels[p]} selected={permissions.includes(p)} onPress={()=>setPermissions(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p])}/>)}</View><Button busy={busy} label="Create role" onPress={()=>void act(()=>communityV9.saveRole({slug,label,color:'#8b5cf6',permissions}),'Role created').then(ok=>{if(ok){setLabel('');setPermissions([]);}})}/></Card>:null}
    {people.data?<Card><Txt variant="heading">Choose a member</Txt><ScrollView horizontal contentContainerStyle={{gap:space.sm}}>{people.data.members.map(p=><Chip key={p.userId} label={p.nickname} selected={selected===p.userId} onPress={()=>setSelected(p.userId)}/>)}</ScrollView>{lead&&data.roles.map(role=><View key={role.id} style={{gap:space.sm}}><Txt>{role.label} · {role.permissions.map(p=>permissionLabels[p]).join(', ')||'Title only'}</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}><Button small disabled={!selected} busy={busy} label="Assign" onPress={()=>void act(()=>communityV9.assignRole(slug,selected,role.id),'Role assigned')}/><Button small variant="secondary" disabled={!selected} busy={busy} label="Revoke" onPress={()=>void act(()=>communityV9.assignRole(slug,selected,role.id,true),'Role removed')}/><Button small variant="danger" busy={busy} label="Delete role" onPress={()=>void act(()=>communityV9.deleteRole(slug,role.id),'Role deleted')}/></View>{data.assignments.filter(a=>a.roleId===role.id).map(a=><Txt key={a.userId} variant="caption" tone="muted">{a.nickname}</Txt>)}</View>)}<Txt variant="heading">Recognize a member</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{(['Helpful member','Kindness','Community star'] as const).map(b=><Chip key={b} label={b} selected={badge===b} onPress={()=>setBadge(b)}/>)}</View><Field label="Why they earned it" value={note} onChangeText={setNote} maxLength={300}/><Button disabled={!selected} busy={busy} label="Grant badge" onPress={()=>void act(()=>communityV9.grantBadge(slug,selected,badge,note),'Achievement granted')}/></Card>:null}
    {lead?<Card><Txt variant="heading">Community verification</Txt><Txt tone="muted">{data.community.verified?'This community is verified.':data.settings.verificationStatus?`Latest request: ${data.settings.verificationStatus}`:'Tell Kamino why this is the official community.'}</Txt><Field label="Supporting details" value={reason} onChangeText={setReason} multiline maxLength={1500}/><Button busy={busy} disabled={data.community.verified} label="Request verification" onPress={()=>void act(()=>communityV9.verify(slug,reason),'Request submitted for review')}/></Card>:null}
  </View>;
}
function Report({slug,act,busy}:{slug:string;act:Act;busy:boolean}){const [open,setOpen]=useState(false),[reason,setReason]=useState('Harassment'),[details,setDetails]=useState('');return <Card><Button variant="ghost" small label="Report this community" onPress={()=>setOpen(v=>!v)}/>{open?<><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{['Harassment','Unsafe content','Spam or scam','Impersonation','Other'].map(r=><Chip key={r} label={r} selected={reason===r} onPress={()=>setReason(r)}/>)}</View><Field label="Details" value={details} onChangeText={setDetails} multiline maxLength={1500}/><Button busy={busy} label="Send report" onPress={()=>void act(()=>communityV9.report(slug,reason,details),'Report sent to Kamino’s safety team').then(ok=>{if(ok){setDetails('');setOpen(false);}})}/></>:null}</Card>;}
function InvitePerson({slug,act,busy}:{slug:string;act:Act;busy:boolean}){const [handle,setHandle]=useState('');return <Card><Txt variant="heading">Invite someone</Txt><Field label="Their @username" value={handle} onChangeText={setHandle} autoCapitalize="none" maxLength={40} placeholder="@username"/><Txt variant="caption" tone="muted">Invitations respect their privacy choices and age eligibility.</Txt><Button small busy={busy} label="Send invitation" onPress={()=>void act(()=>communityV9.invitePerson(slug,handle),'Invitation sent').then(ok=>{if(ok)setHandle('');})}/></Card>;}
export default withCommunityTheme(Tools);
