import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import * as tools from '@/lib/kamino/community-v9';
import { COMMUNITY_PERMISSIONS, type CommunityPermission } from '@/lib/kamino/community-v9-rules';
import { createInvite } from '@/lib/kamino/server';
import { useCurrentUserState } from '@/lib/auth/use-current-user';

const field='mt-1 min-h-11 w-full rounded-xl bg-elevated px-3 py-2 text-sm';
const card='space-y-3 rounded-2xl bg-surface p-4 shadow-border';
const languageOptions=[['en','English'],['es','Español'],['fr','Français'],['de','Deutsch'],['pt','Português'],['hi','हिन्दी'],['ja','日本語'],['ko','한국어'],['zh','中文'],['ar','العربية'],['it','Italiano'],['id','Bahasa Indonesia']];
const permissionLabel:Record<CommunityPermission,string>={post:'Create posts',events:'Create events',live:'Start live rooms',invite:'Invite members',manage_faq:'Edit FAQs',manage_boards:'Manage boards',trusted:'Trusted member'};
type Tab='faq'|'boards'|'quests'|'manage'|'analytics';

export function CommunityTools({slug}:{slug:string}){
  const {user}=useCurrentUserState();
  const q=useQuery({queryKey:['community-tools',slug],queryFn:()=>tools.getCommunityTools({data:slug})});
  const [tab,setTab]=useState<Tab>('faq'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const act=async(fn:()=>Promise<unknown>,message='Saved')=>{setError('');setNotice('');setBusy(true);try{await fn();await q.refetch();setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  const data=q.data;
  if(q.error)return <p className="px-4 py-10 text-sm text-danger">{(q.error as Error).message}</p>;
  if(!data)return <p className="px-4 py-10 text-muted">Loading community space…</p>;
  const member=data.member?.status==='active',lead=member&&['agent','leader'].includes(data.member!.role);
  const tabs:{id:Tab;label:string}[]=[{id:'faq',label:'FAQs'},{id:'boards',label:'Discussion boards'},...(member?[{id:'quests' as const,label:'Quests & rewards'}]:[]),...(data.isModerator?[{id:'manage' as const,label:'Leader tools'},{id:'analytics' as const,label:'Analytics'}]:[])];
  return <div className="space-y-5 px-4 py-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-accent">{data.community.name}</p><h2 className="font-display text-xl font-extrabold">Your community space</h2><p className="text-sm text-muted">Level {data.level} · {data.reputation.toLocaleString()} community reputation</p></div><a className="text-sm font-semibold text-accent" href={`/c/${slug}/events`}>Open calendar</a></div>
    <div className="flex flex-wrap gap-2">{tabs.map(t=><Button key={t.id} size="sm" variant={tab===t.id?'primary':'secondary'} onClick={()=>{setTab(t.id);setNotice('');setError('');}}>{t.label}</Button>)}</div>
    {error?<p role="alert" className="rounded-xl bg-danger/10 p-3 text-sm text-danger">{error}</p>:null}{notice?<p role="status" className="rounded-xl bg-accent/10 p-3 text-sm">{notice}</p>:null}
    {tab==='faq'?<><div className="space-y-3">{data.faqs.map(f=><details key={f.id} className={card}><summary className="cursor-pointer font-semibold">{f.question}</summary><p className="whitespace-pre-wrap text-sm text-muted">{f.answer}</p>{data.permissions.includes('manage_faq')?<Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>tools.deleteCommunityFaq({data:{slug,id:f.id}}),'FAQ removed')}>Remove FAQ</Button>:null}</details>)}{!data.faqs.length?<p className="py-8 text-center text-muted">Answers will appear here as the community grows.</p>:null}</div>{data.permissions.includes('manage_faq')?<form className={card} onSubmit={e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f);void act(()=>tools.saveCommunityFaq({data:{slug,question:String(fd.get('question')),answer:String(fd.get('answer'))}}),'FAQ added').then(()=>f.reset());}}><h3 className="font-semibold">Add an answer</h3><label className="block text-sm">Question<input name="question" required maxLength={200} className={field}/></label><label className="block text-sm">Answer<textarea name="answer" required rows={4} maxLength={4000} className={field}/></label><Button disabled={busy}>Publish FAQ</Button></form>:null}</>:null}
    {tab==='boards'?<Boards slug={slug} boards={data.boards} member={member} canManage={data.permissions.includes('manage_boards')} act={act} busy={busy}/>:null}
    {tab==='quests'?<Quests slug={slug} lead={lead} act={act} busy={busy}/>:null}
    {tab==='analytics'&&data.isModerator?<Analytics slug={slug}/>:null}
    {tab==='manage'&&data.isModerator?<Manage slug={slug} data={data} lead={lead} act={act} busy={busy}/>:null}
    {data.badges.length?<section className={card}><h3 className="font-semibold">Community achievements</h3><div className="grid gap-2 sm:grid-cols-2">{data.badges.map(b=><div key={b.id} className="rounded-xl bg-elevated p-3"><p className="font-semibold">🏅 {b.badge}</p><p className="text-sm text-muted">{b.nickname} · {b.note}</p></div>)}</div></section>:null}
    {member?<InvitePerson slug={slug} act={act} busy={busy}/>:null}
    {user?<Report slug={slug} act={act} busy={busy}/>:null}
  </div>;
}
type Act=(fn:()=>Promise<unknown>,message?:string)=>Promise<void>;
type ToolData=Awaited<ReturnType<typeof tools.getCommunityTools>>;
function Boards({slug,boards,member,canManage,act,busy}:{slug:string;boards:ToolData['boards'];member:boolean;canManage:boolean;act:Act;busy:boolean}){
  const [selected,setSelected]=useState<number|null>(null);
  const list=useQuery({queryKey:['board',slug,selected],queryFn:()=>tools.getBoardThreads({data:{slug,boardId:selected!}}),enabled:selected!==null});
  const posts=useQuery({queryKey:['board-posts',slug],queryFn:()=>tools.getBoardAssignablePosts({data:slug}),enabled:member});
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2">{boards.map(b=><button key={b.id} className={`${card} text-left ${selected===b.id?'ring-2 ring-accent':''}`} onClick={()=>setSelected(b.id)}><h3 className="font-semibold">{b.name}</h3><p className="text-sm text-muted">{b.description}</p><p className="text-xs text-subtle">{b.threadCount} discussions</p></button>)}</div>{!boards.length?<p className="text-muted">A place for each conversation. Leaders can add boards below.</p>:null}
    {selected?<section className={card}><h3 className="font-semibold">{list.data?.board.name??'Discussions'}</h3>{list.error?<p role="alert" className="text-danger">{(list.error as Error).message}</p>:null}{list.data?.threads.map(p=><a key={p.id} href={`/c/${slug}/p/${p.id}`} className="block rounded-xl bg-elevated p-3"><p className="font-semibold">{p.title}</p><p className="text-sm text-muted">{p.excerpt}</p><p className="text-xs text-subtle">{p.nickname} · {p.comments} comments</p></a>)}{list.data?.threads.length===0?<p className="text-sm text-muted">No discussions yet.</p>:null}{member&&posts.data?.length?<form className="space-y-2" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(async()=>{await tools.assignPostBoard({data:{slug,boardId:selected,postId:Number(fd.get('postId')),remove:false}});await list.refetch();},'Discussion added');}}><label className="block text-sm">Add a post to this board<select name="postId" className={field}>{posts.data.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><Button size="sm" disabled={busy}>Add discussion</Button></form>:member?<a className="text-sm text-accent" href={`/new?slug=${slug}`}>Create a post to start a discussion</a>:null}{canManage?<Button variant="secondary" size="sm" disabled={busy} onClick={()=>void act(()=>tools.deleteCommunityBoard({data:{slug,id:selected}}),'Board removed').then(()=>setSelected(null))}>Remove board</Button>:null}</section>:null}
    {canManage?<form className={card} onSubmit={e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f);void act(()=>tools.saveCommunityBoard({data:{slug,name:String(fd.get('name')),description:String(fd.get('description'))}}),'Board created').then(()=>f.reset());}}><h3 className="font-semibold">New discussion board</h3><label className="block text-sm">Name<input required name="name" maxLength={60} className={field}/></label><label className="block text-sm">What belongs here<textarea name="description" maxLength={500} className={field}/></label><Button disabled={busy}>Create board</Button></form>:null}
  </div>;
}
function Quests({slug,lead,act,busy}:{slug:string;lead:boolean;act:Act;busy:boolean}){
  const q=useQuery({queryKey:['quests',slug],queryFn:()=>tools.getCommunityQuests({data:slug})});
  const cosmetics=useQuery({queryKey:['earned-cosmetics'],queryFn:()=>tools.getEarnedCosmetics()});
  return <div className="space-y-4"><p className="text-sm text-muted">Progress counts real participation during each quest. Rewards are earned once and never bought.</p>{q.error?<p className="text-danger">{(q.error as Error).message}</p>:null}{q.data?.map(quest=>{const upcoming=new Date(quest.startsAt)>new Date();return <section key={quest.id} className={card}><p className="text-xs font-bold text-accent uppercase">{quest.kind}</p><h3 className="font-semibold">{quest.title}</h3><p className="text-sm text-muted">{quest.description}</p><p className="text-sm">{quest.progress} / {quest.target} {quest.metric.replace('_',' ')} · 🏅 {quest.badge}</p><progress className="h-2 w-full accent-accent" max={quest.target} value={Math.min(quest.progress,quest.target)}/><p className="text-xs text-subtle">{new Date(quest.startsAt).toLocaleDateString()}{quest.endsAt?` – ${new Date(quest.endsAt).toLocaleDateString()}`:''}{quest.rewardCosmetic?` · ${quest.rewardCosmetic} chat colour`:''}</p><Button size="sm" disabled={busy||!!quest.claimedAt||upcoming||quest.progress<quest.target} onClick={()=>void act(async()=>{await tools.claimCommunityQuest({data:{slug,id:quest.id}});await q.refetch();await cosmetics.refetch();},'Reward earned')}>{quest.claimedAt?'Reward earned':upcoming?'Starts soon':'Claim reward'}</Button></section>;})}{q.data?.length===0?<p className="text-muted">No quests yet. Check back for the community’s next goal.</p>:null}
    {cosmetics.data?.length?<section className={card}><h3 className="font-semibold">Your earned colours</h3><div className="flex flex-wrap gap-2">{cosmetics.data.map(c=><Button key={c.cosmetic} size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>tools.equipEarnedCosmetic({data:{cosmetic:c.cosmetic as 'aurora'|'sunrise'|'ocean'|'forest'}}),'Chat colour equipped')}>{c.cosmetic}</Button>)}</div></section>:null}
    {lead?<form className={card} onSubmit={e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f);void act(async()=>{await tools.saveCommunityQuest({data:{slug,title:String(fd.get('title')),description:String(fd.get('description')),kind:String(fd.get('kind')) as 'quest'|'weekly'|'seasonal'|'milestone',metric:String(fd.get('metric')) as 'posts'|'comments'|'likes_received'|'checkins',target:Number(fd.get('target')),badge:String(fd.get('badge')),rewardCosmetic:String(fd.get('cosmetic')) as ''|'aurora'|'sunrise'|'ocean'|'forest',startsAt:new Date(String(fd.get('start'))).toISOString(),endsAt:fd.get('end')?new Date(String(fd.get('end'))).toISOString():undefined}});await q.refetch();},'Quest published').then(()=>f.reset());}}><h3 className="font-semibold">Set a community goal</h3><label className="block text-sm">Title<input name="title" required maxLength={100} className={field}/></label><label className="block text-sm">Description<textarea name="description" className={field}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Type<select name="kind" className={field}><option value="quest">Quest</option><option value="weekly">Weekly mission</option><option value="seasonal">Seasonal event</option><option value="milestone">Member milestone</option></select></label><label className="text-sm">Count<select name="metric" className={field}><option value="posts">Posts</option><option value="comments">Comments</option><option value="likes_received">Likes received</option><option value="checkins">Daily check-ins</option></select></label><label className="text-sm">Goal<input name="target" type="number" min={1} max={1000} defaultValue={5} className={field}/></label><label className="text-sm">Badge name<input name="badge" required maxLength={60} className={field}/></label><label className="text-sm">Starts<input name="start" type="datetime-local" required className={field}/></label><label className="text-sm">Ends<input name="end" type="datetime-local" className={field}/></label></div><label className="block text-sm">Optional colour reward<select name="cosmetic" className={field}><option value="">Badge only</option>{['aurora','sunrise','ocean','forest'].map(v=><option key={v} value={v}>{v}</option>)}</select></label><Button disabled={busy}>Publish goal</Button></form>:null}
  </div>;
}
function Analytics({slug}:{slug:string}){
  const q=useQuery({queryKey:['community-analytics',slug],queryFn:()=>tools.getCommunityAnalytics({data:slug})});
  if(q.error)return <p className="text-danger">{(q.error as Error).message}</p>;if(!q.data)return <p className="text-muted">Loading analytics…</p>;const data=q.data;
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[['Members',data.members],['Joined in 30 days',data.newMembers30],['Daily active',data.dailyActive],['Weekly active',data.weeklyActive],['Monthly active',data.monthlyActive],['30-day retention',data.retentionPercent===null?'Not enough history':`${data.retentionPercent}%`]].map(([label,value])=><div key={label} className={card}><p className="text-xs text-muted">{label}</p><p className="font-display text-xl font-extrabold">{value}</p></div>)}</div><p className="text-xs text-muted">{data.definition}</p><section className={card}><h3 className="font-semibold">Member growth</h3>{data.growth.length?<div className="space-y-2">{data.growth.map(d=><div key={d.day} className="flex items-center gap-3 text-sm"><span className="w-24 text-muted">{d.day}</span><div className="h-3 rounded-full bg-accent" style={{width:`${Math.max(2,d.count/Math.max(...data.growth.map(x=>x.count))*60)}%`}}/><span>{d.count}</span></div>)}</div>:<p className="text-sm text-muted">No joins in the last 30 days.</p>}</section><section className={card}><h3 className="font-semibold">Top content · last 30 days</h3>{data.topContent.map(p=><a key={p.id} href={`/c/${slug}/p/${p.id}`} className="block rounded-xl bg-elevated p-3"><p className="font-semibold">{p.title}</p><p className="text-xs text-muted">{p.nickname} · {p.likes} likes · {p.comments} comments</p></a>)}{!data.topContent.length?<p className="text-sm text-muted">Content will appear as members participate.</p>:null}</section></div>;
}
function Manage({slug,data,lead,act,busy}:{slug:string;data:ToolData;lead:boolean;act:Act;busy:boolean}){
  const [permissions,setPermissions]=useState<CommunityPermission[]>([]),[invite,setInvite]=useState('');
  const people=useQuery({queryKey:['mod-details',slug],queryFn:()=>tools.getCommunityModerationDetails({data:slug})});
  return <div className="space-y-4"><a className="text-sm font-bold text-accent" href={`/c/${slug}/mod`}>Open reports, bans and appeals →</a>
    {lead?<form className={card} onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(()=>tools.saveCommunityPolicies({data:{slug,language:String(fd.get('language')),localArea:String(fd.get('localArea')||''),memberLimit:fd.get('memberLimit')?Number(fd.get('memberLimit')):null,joinPolicy:String(fd.get('join')) as 'open'|'approval'|'invite',postPolicy:String(fd.get('post')) as 'members'|'trusted'|'moderators',livePolicy:String(fd.get('live')) as 'members'|'trusted'|'moderators',eventPolicy:String(fd.get('event')) as 'members'|'trusted'|'moderators',keywordFilters:String(fd.get('keywords')).split('\n').map(x=>x.trim()).filter(Boolean)}}));}}><h3 className="font-semibold">Community permissions</h3><label className="block text-sm">Language<select name="language" defaultValue={data.settings.language} className={field}>{languageOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="block text-sm">Local area (optional)<input name="localArea" defaultValue={data.settings.localArea} placeholder="City or region" maxLength={150} className={field}/></label><label className="block text-sm">Micro-community member limit<input name="memberLimit" type="number" min={10} max={50} defaultValue={data.settings.memberLimit??undefined} placeholder="No limit" className={field}/><span className="text-xs text-muted">Optional. Keep a small community of 10–50 members.</span></label><label className="block text-sm">Joining<select name="join" defaultValue={data.settings.joinPolicy} className={field}><option value="open">Open joining</option><option value="approval">Leader approval</option><option value="invite">Invite only</option></select></label>{[['post','Posting',data.settings.postPolicy],['live','Starting live rooms',data.settings.livePolicy],['event','Creating events',data.settings.eventPolicy]].map(([name,label,value])=><label key={name} className="block text-sm">{label}<select name={name} defaultValue={value} className={field}><option value="members">All members</option><option value="trusted">Trusted members and moderators</option><option value="moderators">Moderators and assigned roles</option></select></label>)}<label className="block text-sm">Blocked words or phrases<textarea name="keywords" defaultValue={data.settings.keywordFilters.join('\n')} rows={4} className={field}/><span className="text-xs text-muted">One phrase per line. Applied to new member posts and events.</span></label><Button disabled={busy}>Save permissions</Button></form>:null}
    {lead?<section className={card}><h3 className="font-semibold">Invite link</h3><p className="text-sm text-muted">Invite links let someone join an invite-only community. Share only with people you want to invite.</p>{invite?<input readOnly aria-label="Invite link" value={invite} className={field} onFocus={e=>e.currentTarget.select()}/>:null}<Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(async()=>{const result=await createInvite({data:{slug,maxUses:20}});setInvite(`${window.location.origin}/join?code=${encodeURIComponent(result.code)}`);},'Invite link ready')}>Create invite link</Button></section>:null}
    {lead?<form className={card} onSubmit={e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f);void act(()=>tools.saveCommunityRole({data:{slug,label:String(fd.get('label')),color:String(fd.get('color')),permissions}}),'Role created').then(()=>{f.reset();setPermissions([]);});}}><h3 className="font-semibold">Custom roles with permissions</h3><label className="block text-sm">Role name<input name="label" required maxLength={40} placeholder="Trusted member, Expert, Creator…" className={field}/></label><label className="block text-sm">Colour<input name="color" type="color" defaultValue="#8b5cf6" className="mt-1 h-11 w-20 rounded-lg"/></label><div className="grid gap-2 sm:grid-cols-2">{COMMUNITY_PERMISSIONS.map(p=><label key={p} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={permissions.includes(p)} onChange={e=>setPermissions(v=>e.target.checked?[...v,p]:v.filter(x=>x!==p))}/>{permissionLabel[p]}</label>)}</div><Button disabled={busy}>Create role</Button></form>:null}
    {lead&&data.roles.length&&people.data?<section className={card}><h3 className="font-semibold">Assign community roles</h3>{data.roles.map(role=><div key={role.id} className="space-y-2 rounded-xl bg-elevated p-3"><p className="font-semibold" style={{color:role.color}}>{role.label}</p><p className="text-xs text-muted">{role.permissions.map(p=>permissionLabel[p]).join(' · ')||'Title only'}</p>{data.assignments.filter(a=>a.roleId===role.id).map(a=><div key={a.userId} className="flex items-center justify-between gap-2 text-sm"><span>{a.nickname}</span><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>tools.assignCommunityRole({data:{slug,userId:a.userId,roleId:role.id,remove:true}}),'Role removed')}>Remove</Button></div>)}<form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(()=>tools.assignCommunityRole({data:{slug,roleId:role.id,userId:String(fd.get('userId')),remove:false}}),'Role assigned');}}><select name="userId" className={`${field} min-w-0 flex-1`}>{people.data!.members.map(p=><option key={p.userId} value={p.userId}>{p.nickname}</option>)}</select><Button size="sm" disabled={busy}>Assign</Button></form><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>tools.deleteCommunityRole({data:{slug,id:role.id}}),'Role deleted')}>Delete role</Button></div>)}</section>:null}
    {people.data?<form className={card} onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(()=>tools.grantCommunityBadge({data:{slug,userId:String(fd.get('userId')),badge:String(fd.get('badge')) as 'Helpful member'|'Kindness'|'Community star',note:String(fd.get('note'))}}),'Achievement granted');}}><h3 className="font-semibold">Recognize a member</h3><label className="block text-sm">Member<select name="userId" className={field}>{people.data.members.map(p=><option key={p.userId} value={p.userId}>{p.nickname}</option>)}</select></label><label className="block text-sm">Badge<select name="badge" className={field}>{['Helpful member','Kindness','Community star'].map(b=><option key={b}>{b}</option>)}</select></label><label className="block text-sm">Why they earned it<textarea required name="note" maxLength={300} className={field}/></label><Button disabled={busy}>Grant badge</Button></form>:null}
    {lead?<form className={card} onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(()=>tools.requestCommunityVerification({data:{slug,reason:String(fd.get('reason'))}}),'Verification request submitted for review');}}><h3 className="font-semibold">Community verification</h3><p className="text-sm text-muted">{data.community.verified?'This community is verified.':data.settings.verificationStatus?`Latest request: ${data.settings.verificationStatus}`:'Tell the Kamino team why this is the official community.'}</p><label className="block text-sm">Supporting details<textarea name="reason" required minLength={10} maxLength={1500} className={field}/></label><Button disabled={busy||data.community.verified}>Request verification</Button></form>:null}
  </div>;
}
function Report({slug,act,busy}:{slug:string;act:Act;busy:boolean}){
  return <details className={card}><summary className="cursor-pointer text-sm font-semibold text-muted">Report this community</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(()=>tools.reportCommunityV9({data:{slug,reason:String(fd.get('reason')),details:String(fd.get('details'))}}),'Report sent to Kamino’s safety team');}}><label className="block text-sm">Reason<select name="reason" className={field}>{['Harassment','Unsafe content','Spam or scam','Impersonation','Other'].map(r=><option key={r}>{r}</option>)}</select></label><label className="block text-sm">Details<textarea name="details" maxLength={1500} className={field}/></label><Button size="sm" disabled={busy}>Send report</Button></form></details>;
}
function InvitePerson({slug,act,busy}:{slug:string;act:Act;busy:boolean}){return <details className={card}><summary className="cursor-pointer text-sm font-semibold">Invite someone to this community</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(()=>tools.inviteCommunityPerson({data:{slug,handle:String(fd.get('handle'))}}),'Invitation sent');}}><label className="block text-sm">Their @username<input name="handle" required maxLength={40} placeholder="@username" className={field}/></label><p className="text-xs text-muted">Invitations respect their privacy choices and age eligibility.</p><Button size="sm" disabled={busy}>Send invitation</Button></form></details>;}
