import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { ChallengePanel } from '@/components/challenge-panel';
import { Button } from '@/components/ui/button';
import * as api from '@/lib/kamino/community-v9';
import { EventParticipation } from '@/components/social-events-v10';
import { localToInstant, zonedLocalInput, type Disambiguation } from '@/lib/kamino/event-time-v10';
import { canLead } from '@/lib/kamino/safety';
type Event=Awaited<ReturnType<typeof api.listExpandedEvents>>['events'][number];
const field='mt-1 min-h-11 w-full rounded-xl bg-elevated px-3 py-2 text-sm';
export function CommunityEvents({slug}:{slug:string}){
  const q=useQuery({queryKey:['events',slug],queryFn:()=>api.listExpandedEvents({data:slug})});
  const [editor,setEditor]=useState<Event|'new'|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[attendees,setAttendees]=useState<{id:number;rows:Awaited<ReturnType<typeof api.getEventAttendees>>}|null>(null),[calendar,setCalendar]=useState(false),[month,setMonth]=useState(()=>new Date()),[participation,setParticipation]=useState<number|null>(null),[scopes,setScopes]=useState<Record<number,'single'|'future'|'all'>>({});
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await q.refetch();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  if(q.error)return <p className="px-4 py-10 text-danger">{(q.error as Error).message}</p>;if(!q.data)return <p className="px-4 py-10 text-muted">Loading events…</p>;
  const data=q.data,member=data.member?.status==='active',lead=canLead(data.member?.role);
  const download=async(event:Event)=>{const result=await api.getEventCalendar({data:{slug,id:event.id}});const url=URL.createObjectURL(new Blob([result.content],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const daysInMonth=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),firstDay=new Date(month.getFullYear(),month.getMonth(),1).getDay();
  return <div className="space-y-4 px-4 py-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-xl font-extrabold">Events & challenges</h2><p className="text-sm text-muted">Make plans, meet your people and share what you’re creating.</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>setCalendar(v=>!v)}>{calendar?'List view':'Month view'}</Button>{data.canCreate?<Button size="sm" onClick={()=>setEditor(editor?null:'new')}>{editor?'Close editor':'Create event'}</Button>:null}</div></div>{error?<p role="alert" className="rounded-xl bg-danger/10 p-3 text-sm text-danger">{error}</p>:null}
    {editor?<EventEditor slug={slug} event={editor==='new'?undefined:editor} busy={busy} save={d=>act(async()=>{await api.saveExpandedEvent({data:d});setEditor(null);})}/>:null}
    {calendar?<section className="rounded-2xl bg-surface p-4 shadow-border"><div className="mb-3 flex items-center justify-between gap-2"><Button size="sm" variant="secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>Previous</Button><h3 className="text-sm font-bold">{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><Button size="sm" variant="secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>Next</Button></div><div className="grid grid-cols-7 gap-1">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><p key={day} className="py-2 text-center text-[10px] font-bold text-subtle">{day}</p>)}{Array.from({length:firstDay},(_,i)=><div key={`blank-${i}`}/>)}{Array.from({length:daysInMonth},(_,i)=>{const day=i+1,events=data.events.filter(ev=>{const d=new Date(ev.startsAt);return d.getFullYear()===month.getFullYear()&&d.getMonth()===month.getMonth()&&d.getDate()===day&&ev.status!=='cancelled';});return <div key={day} className="min-h-16 min-w-0 rounded-lg bg-elevated p-1"><p className="text-xs font-bold">{day}</p>{events.map(ev=><a key={ev.id} href={`#event-${ev.id}`} className="mt-1 block truncate rounded bg-accent/15 px-1 text-[10px] font-semibold text-accent" title={ev.title}>{ev.title}</a>)}</div>;})}</div></section>:null}
    <div className="space-y-4">{data.events.map(event=><article key={event.id} id={`event-${event.id}`} className="scroll-mt-24 overflow-hidden rounded-2xl bg-surface shadow-border">{event.imageUrl?<img src={event.imageUrl} alt={`${event.title} event banner`} className="h-40 w-full object-cover" loading="lazy"/>:null}<div className="space-y-3 p-4"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-accent/10 px-2 py-1 text-accent">{event.kind==='challenge'?'Challenge':event.venueKind==='in_person'?'In person':'Online'}</span>{event.status==='cancelled'?<span className="rounded-full bg-danger/10 px-2 py-1 text-danger">Cancelled</span>:null}{event.recurrence!=='none'?<span className="rounded-full bg-elevated px-2 py-1 text-muted">Repeats {event.recurrence}</span>:null}</div><h3 className="font-display text-lg font-extrabold">{event.title}</h3><p className="whitespace-pre-wrap text-sm text-muted">{event.body}</p><p className="text-xs text-muted">Event time zone: {event.timezone}</p><p className="text-sm font-semibold">{new Date(event.startsAt).toLocaleString()}{event.endsAt?` – ${new Date(event.endsAt).toLocaleString()}`:''}</p>{event.location?<p className="text-sm text-muted">📍 {event.location}</p>:null}{event.onlineUrl&&event.status!=='cancelled'?<a href={event.onlineUrl} target="_blank" rel="noreferrer" className="inline-block text-sm font-bold text-accent">Open event link ↗</a>:null}
      {event.kind==='challenge'?<ChallengePanel slug={slug} event={event} isMember={member} isLeader={lead} onChanged={()=>void q.refetch()}/>:null}
      <div className="flex flex-wrap gap-2">{member&&event.status!=='cancelled'?<><Button size="sm" disabled={busy} variant={event.myResponse==='going'?'primary':'secondary'} onClick={()=>void act(()=>api.respondExpandedEvent({data:{slug,id:event.id,response:event.myResponse==='going'?'none':'going'}}))}>{event.myResponse==='going'?'Going ✓':'Going'}</Button><Button size="sm" disabled={busy} variant={event.myResponse==='interested'?'primary':'secondary'} onClick={()=>void act(()=>api.respondExpandedEvent({data:{slug,id:event.id,response:event.myResponse==='interested'?'none':'interested'}}))}>{event.myResponse==='interested'?'Interested ✓':'Interested'}</Button></>:null}<Button size="sm" variant="secondary" onClick={()=>void act(()=>download(event))}>Add to calendar</Button>{member?<Button size="sm" variant="secondary" onClick={()=>void act(async()=>setAttendees({id:event.id,rows:await api.getEventAttendees({data:{slug,id:event.id}})}))}>{event.rsvpCount} going · {event.interestedCount} interested</Button>:<p className="self-center text-xs text-muted">{event.rsvpCount} going · {event.interestedCount} interested</p>}{member&&event.chatRoomId?<a href={`/chats/${event.chatRoomId}`} className="self-center px-2 text-sm font-bold text-accent">{event.liveRoomId?'Event live room':'Event chat'} →</a>:null}</div>
      {attendees?.id===event.id?<section className="rounded-xl bg-elevated p-3"><div className="flex justify-between"><p className="text-sm font-semibold">Attendees</p><button className="text-sm text-accent" onClick={()=>setAttendees(null)}>Close</button></div>{attendees.rows.length?attendees.rows.map(p=><a key={p.userId} href={`/u/${p.handle}`} className="mt-2 block text-sm">{p.nickname} · {p.response}</a>):<p className="mt-2 text-sm text-muted">Be the first to make plans.</p>}</section>:null}
      {member?<Button size="sm" variant="secondary" onClick={()=>setParticipation(v=>v===event.id?null:event.id)}>{participation===event.id?'Close updates':'Updates & attendance'}</Button>:null}{participation===event.id?<EventParticipation slug={slug} eventId={event.id}/>:null}
      {event.canEdit?<div className="flex flex-wrap gap-2 border-t border-border pt-3">{event.seriesId?<label className="text-sm">Change scope<select aria-label={`Change scope for ${event.title}`} value={scopes[event.id]??'single'} onChange={e=>setScopes(v=>({...v,[event.id]:e.target.value as 'single'|'future'|'all'}))} className={field}><option value="single">This occurrence</option><option value="future">This and later</option><option value="all">Entire series</option></select></label>:null}{event.status!=='cancelled'?<><Button size="sm" variant="secondary" disabled={busy} onClick={()=>setEditor(event)}>Edit event</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>{if(window.confirm(`Cancel “${event.title}” and notify attendees?`))void act(()=>api.manageExpandedEvent({data:{slug,id:event.id,action:'cancel',scope:scopes[event.id]??'single'}}));}}>Cancel event</Button></>:null}<Button size="sm" variant="secondary" disabled={busy} onClick={()=>{if(window.confirm(`Delete “${event.title}”? This removes the event and RSVPs.`))void act(()=>api.manageExpandedEvent({data:{slug,id:event.id,action:'delete',scope:scopes[event.id]??'single'}}));}}>Delete</Button></div>:null}
    </div></article>)}</div>{!data.events.length?<p className="py-10 text-center text-muted">No plans yet. The next community gathering starts here.</p>:null}
  </div>;
}
function EventEditor({slug,event,busy,save}:{slug:string;event?:Event;busy:boolean;save:(d:Parameters<typeof api.saveExpandedEvent>[0]['data'])=>Promise<void>}){
  const [timezone,setTimezone]=useState(event?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone??'UTC'),[error,setError]=useState('');
  const initial=(value:string|null)=>value?zonedLocalInput(value,event?.timezone??timezone):'';
  return <form key={event?.id??'new'} className="space-y-3 rounded-2xl bg-surface p-4 shadow-border" onSubmit={e=>{
    e.preventDefault();setError('');const fd=new FormData(e.currentTarget);
    try{
      const dstDisambiguation=String(fd.get('dst')||'reject') as Disambiguation;
      const startsAt=localToInstant(String(fd.get('startsAt')),timezone,dstDisambiguation),endsAt=fd.get('endsAt')?localToInstant(String(fd.get('endsAt')),timezone,dstDisambiguation):undefined;
      void save({slug,id:event?.id,title:String(fd.get('title')),body:String(fd.get('body')),kind:String(fd.get('kind')) as 'event'|'challenge',startsAt,endsAt,venueKind:String(fd.get('venue')) as 'online'|'in_person',onlineUrl:String(fd.get('url')),location:String(fd.get('location')),imageUrl:String(fd.get('image')),recurrence:String(fd.get('recurrence')||'none') as 'none'|'daily'|'weekly'|'monthly',repeatCount:Number(fd.get('count')||1),createChat:fd.get('chat')==='on',createLive:fd.get('live')==='on',timezone,dstDisambiguation,scope:String(fd.get('scope')||'single') as 'single'|'future'|'all'});
    }catch(err){setError(err instanceof Error?err.message:'Choose valid dates.');}
  }}><h3 className="font-semibold">{event?'Edit event':'Make a plan'}</h3>{error?<p role="alert" className="text-sm text-danger">{error}</p>:null}
    <label className="block text-sm">Title<input name="title" required maxLength={120} defaultValue={event?.title} className={field}/></label>
    <label className="block text-sm">Details<textarea name="body" maxLength={3000} rows={3} defaultValue={event?.body} className={field}/></label>
    <label className="block text-sm">Event time zone<input value={timezone} onChange={e=>setTimezone(e.target.value)} required placeholder="America/Vancouver" className={field}/></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Starts in event time zone<input type="datetime-local" name="startsAt" required defaultValue={initial(event?.startsAt??null)} className={field}/></label><label className="text-sm">Ends in event time zone<input type="datetime-local" name="endsAt" defaultValue={initial(event?.endsAt??null)} className={field}/></label>
    <label className="text-sm">Repeated clock times<select name="dst" defaultValue={event?.dstDisambiguation??'reject'} className={field}><option value="reject">Ask me to resolve ambiguous times</option><option value="earlier">Use the earlier clock occurrence</option><option value="later">Use the later clock occurrence</option></select></label>
    <label className="text-sm">Type<select name="kind" defaultValue={event?.kind??'event'} disabled={!!event} className={field}><option value="event">Event</option><option value="challenge">Challenge</option></select>{event?<input type="hidden" name="kind" value={event.kind}/>:null}</label>
    <label className="text-sm">Where<select name="venue" defaultValue={event?.venueKind??'online'} className={field}><option value="online">Online</option><option value="in_person">In person</option></select></label></div>
    <label className="block text-sm">Online event link<input type="url" name="url" placeholder="https://…" defaultValue={event?.onlineUrl} className={field}/></label><label className="block text-sm">Location<input name="location" placeholder="Venue, address or meeting point" defaultValue={event?.location} className={field}/></label><label className="block text-sm">Banner image link<input type="url" name="image" placeholder="https://…" defaultValue={event?.imageUrl} className={field}/></label>
    {event?.seriesId?<label className="block text-sm">Apply edits to<select name="scope" className={field}><option value="single">This occurrence</option><option value="future">This and later occurrences</option><option value="all">Entire series</option></select></label>:null}
    {!event?<><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Repeats<select name="recurrence" className={field}><option value="none">One time</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className="text-sm">Number of occurrences<input type="number" name="count" min={1} max={12} defaultValue={4} className={field}/></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="chat"/>Create an event chat</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="live"/>Create a scheduled live room</label></>:null}
    <p className="text-xs text-muted">Repeats preserve the event’s local clock time across daylight-saving changes. Times skipped when clocks move forward must be changed before publishing.</p>
    <Button disabled={busy}>{busy?'Saving…':event?'Save event':'Publish event'}</Button></form>;
}
