import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { appointCommunityLeader,getCommunityModerationDetails } from '@/lib/kamino/community-v9';
import { setMemberRole } from '@/lib/kamino/server';
import { clearMute,issueMute,resolveAppeal } from '@/lib/kamino/extras';
const field='min-h-11 w-full rounded-xl bg-elevated px-3 py-2 text-sm';
export function CommunityModerationV9({slug}:{slug:string}){
  const q=useQuery({queryKey:['mod-details',slug],queryFn:()=>getCommunityModerationDetails({data:slug})});const [error,setError]=useState(''),[busy,setBusy]=useState(false),[person,setPerson]=useState(''),[reason,setReason]=useState(''),[hours,setHours]=useState(24);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await q.refetch();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  if(!q.data)return null;const data=q.data,lead=['agent','leader'].includes(data.role);return <div className="space-y-5"><a href={`/c/${slug}/tools`} className="inline-block rounded-xl bg-accent/10 px-4 py-3 text-sm font-bold text-accent">Community permissions, roles, quests & analytics →</a>{error?<p role="alert" className="text-sm text-danger">{error}</p>:null}
    <section className="space-y-3 rounded-2xl bg-surface p-4 shadow-border"><h2 className="font-display text-lg font-bold">Ban list</h2><p className="text-sm text-muted">Removed members remain listed so leaders can restore access.</p>{data.banned.map(p=><div key={p.userId} className="flex items-center justify-between gap-3 rounded-xl bg-elevated p-3"><div><p className="font-semibold">{p.nickname}</p><p className="text-xs text-subtle">@{p.handle}</p></div>{lead?<Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>setMemberRole({data:{slug,userId:p.userId,action:'unban'}}))}>Restore member</Button>:null}</div>)}{!data.banned.length?<p className="text-sm text-muted">No banned members.</p>:null}</section>
    <section className="space-y-3 rounded-2xl bg-surface p-4 shadow-border"><h2 className="font-display text-lg font-bold">Member permissions & timed mutes</h2><label className="block text-sm">Member<select className={`mt-1 ${field}`} value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose a member</option>{data.members.map(p=><option key={p.userId} value={p.userId}>{p.nickname} · {p.role==='agent'?'Owner':p.role==='leader'?'Co-leader':p.role==='curator'?'Moderator':'Member'}</option>)}</select></label>{lead?<div className="flex flex-wrap gap-2">{(['leader','curator','member'] as const).map(role=><Button key={role} size="sm" variant="secondary" disabled={busy||!person||role==='leader'&&data.role!=='agent'} onClick={()=>void act(()=>appointCommunityLeader({data:{slug,userId:person,role}}))}>{role==='leader'?'Appoint co-leader':role==='curator'?'Make moderator':'Make member'}</Button>)}</div>:null}<label className="block text-sm">Reason for mute<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={300} className={`mt-1 ${field}`}/></label><label className="block text-sm">Duration<select value={hours} onChange={e=>setHours(Number(e.target.value))} className={`mt-1 ${field}`}><option value={1}>1 hour</option><option value={24}>24 hours</option><option value={72}>3 days</option><option value={168}>7 days</option></select></label><Button size="sm" disabled={busy||!person||reason.trim().length<3} onClick={()=>void act(()=>issueMute({data:{slug,userId:person,hours,reason}}))}>Mute member</Button>{data.mutes.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-elevated p-3"><div><p className="text-sm font-semibold">{m.nickname}</p><p className="text-xs text-muted">{m.reason} · until {new Date(m.until).toLocaleString()}</p></div><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>clearMute({data:{slug,userId:m.userId}}))}>Clear mute</Button></div>)}</section>
    <section className="space-y-3 rounded-2xl bg-surface p-4 shadow-border"><h2 className="font-display text-lg font-bold">Appeals</h2>{data.appeals.map(a=><form key={a.id} className="space-y-2 rounded-xl bg-elevated p-3" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void act(()=>resolveAppeal({data:{slug,appealId:a.id,decision:String(fd.get('decision')) as 'upheld'|'overturned',note:String(fd.get('note'))}}));}}><p className="text-sm font-semibold">{a.nickname} · {a.kind} · {a.status}</p><p className="text-sm text-muted">{a.message}</p>{a.decisionNote?<p className="text-sm">Decision: {a.decisionNote}</p>:null}{a.status==='open'&&lead?<><label className="block text-sm">Decision<select name="decision" className={field}><option value="overturned">Accept appeal</option><option value="upheld">Keep moderation decision</option></select></label><label className="block text-sm">Message to member<textarea name="note" maxLength={300} className={field}/></label><Button size="sm" disabled={busy}>Submit decision</Button></>:null}</form>)}{!data.appeals.length?<p className="text-sm text-muted">No appeals yet.</p>:null}</section>
    <details className="rounded-2xl bg-surface p-4 shadow-border"><summary className="cursor-pointer font-display text-lg font-bold">Moderator activity log</summary><div className="mt-3 space-y-2">{data.audit.map(a=><div key={a.id} className="rounded-xl bg-elevated p-3"><p className="text-sm font-semibold">{a.actor} · {a.action.replaceAll(':',' · ')}</p><p className="break-words text-xs text-muted">{a.detail}</p><p className="text-xs text-subtle">{new Date(a.createdAt).toLocaleString()}</p></div>)}</div></details>
  </div>;
}
