import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import * as api from '@/lib/kamino/social-events-v10';
import { updateGroupChat } from '@/lib/kamino/content-v9';

const card='min-w-0 space-y-3 rounded-2xl border border-border bg-surface p-4 [overflow-wrap:anywhere]';
const field='min-h-11 w-full rounded-xl border border-border bg-elevated px-3 py-2';
export function Connections(){
  const q=useQuery({queryKey:['friendships'],queryFn:()=>api.getFriendships()}),invites=useQuery({queryKey:['groupInvitations'],queryFn:()=>api.getGroupInvitations()});
  const [handle,setHandle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await Promise.all([q.refetch(),invites.refetch()]);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  return <div className="mx-auto max-w-3xl space-y-5"><header><h1 className="text-2xl font-extrabold">Your connections</h1><p className="mt-2 text-muted">Friendships start with a request. Group invitations join your inbox only when you accept.</p></header><form className={card} onSubmit={e=>{e.preventDefault();void act(async()=>{await api.sendFriendRequest({data:{handle}});setHandle('');});}}><label className="block text-sm font-semibold">Member username<input className={`${field} mt-2`} value={handle} onChange={e=>setHandle(e.target.value)} placeholder="@username" required maxLength={31}/></label><Button disabled={busy}>Send friend request</Button></form>{error||q.error||invites.error?<p role="alert" className="text-danger">{error||q.error?.message||invites.error?.message}</p>:null}{q.isPending||invites.isPending?<p role="status">Loading connections…</p>:null}
    <section className={card}><h2 className="text-lg font-bold">Friend requests</h2>{q.data?.incoming.length?q.data.incoming.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-border py-3"><a href={`/u/${p.handle}`}>{p.name} <span className="text-muted">@{p.handle}</span></a><div className="flex gap-2"><Button size="sm" disabled={busy} onClick={()=>void act(()=>api.respondFriendRequest({data:{requestId:p.id,action:'accept'}}))}>Accept</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>api.respondFriendRequest({data:{requestId:p.id,action:'decline'}}))}>Decline</Button></div></div>):<p className="text-sm text-muted">No pending requests.</p>}{q.data?.outgoing.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-border py-3"><p>Waiting for {p.name}</p><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>api.respondFriendRequest({data:{requestId:p.id,action:'cancel'}}))}>Cancel request</Button></div>)}</section>
    <section className={card}><h2 className="text-lg font-bold">Group invitations</h2>{invites.data?.length?invites.data.map(i=><div key={i.id} className="space-y-2 border-t border-border py-3"><p className="font-semibold">{i.name}</p><p className="text-sm text-muted">Invited by {i.inviter} · expires {new Date(i.expiresAt).toLocaleDateString()}</p><div className="flex gap-2"><Button size="sm" disabled={busy} onClick={()=>void act(()=>api.respondGroupInvitation({data:{invitationId:i.id,accept:true}}))}>Accept invitation</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>api.respondGroupInvitation({data:{invitationId:i.id,accept:false}}))}>Decline</Button></div></div>):<p className="text-sm text-muted">No group invitations.</p>}</section>
    <section className={card}><h2 className="text-lg font-bold">Friends</h2>{q.data?.friends.length?q.data.friends.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-border py-3"><a className="font-semibold text-accent" href={`/u/${p.handle}`}>{p.name} · @{p.handle}</a><Button size="sm" variant="secondary" disabled={busy} onClick={()=>{if(window.confirm(`Remove ${p.name} from friends?`))void act(()=>api.respondFriendRequest({data:{requestId:p.id,action:'remove'}}));}}>Remove friend</Button></div>):<p className="text-sm text-muted">Accepted friendships appear here.</p>}</section>
  </div>;
}
export function GroupManagement({roomId}:{roomId:number}){
  const q=useQuery({queryKey:['groupManagement',roomId],queryFn:()=>api.getGroupManagement({data:{roomId}})}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[handle,setHandle]=useState('');
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await q.refetch();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  if(q.isPending)return <p role="status">Loading group…</p>;if(q.error||!q.data)return <p role="alert">{q.error?.message}</p>;const group=q.data,admin=['owner','coadmin'].includes(group.role);
  return <div className="mx-auto max-w-3xl space-y-4"><header><h1 className="text-2xl font-extrabold">{group.name}</h1><p className="mt-2 text-muted">Your role: {group.role}. Moderators can pin messages and remove members. Co-admins can also invite and rename.</p><a className="mt-3 inline-block font-bold text-accent" href={`/chats/${roomId}`}>Open conversation →</a></header>{error?<p role="alert" className="text-danger">{error}</p>:null}{admin?<><form className={card} onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name'));void act(()=>updateGroupChat({data:{roomId,name}}));}}><label className="block">Group name<input className={`${field} mt-2`} name="name" defaultValue={group.name} maxLength={70} required/></label><Button disabled={busy}>Save name</Button></form><form className={card} onSubmit={e=>{e.preventDefault();void act(async()=>{await api.inviteToGroup({data:{roomId,handle}});setHandle('');});}}><label className="block">Invite a member<input className={`${field} mt-2`} value={handle} onChange={e=>setHandle(e.target.value)} placeholder="@username" required/></label><Button disabled={busy}>Send invitation</Button><p className="text-sm text-muted">They can read the conversation after accepting.</p></form></>:null}
    <section className={card}><h2 className="font-bold">Members</h2>{group.people.map(p=><div key={p.userId} className="space-y-2 border-t border-border py-3"><a href={`/u/${p.handle}`} className="font-semibold">{p.name} · {p.role}</a><div className="flex flex-wrap gap-2">{group.role==='owner'&&p.role!=='owner'?<label className="text-sm">Role<select aria-label={`Role for ${p.name}`} disabled={busy} value={p.role} className={`${field} mt-1`} onChange={e=>void act(()=>api.setGroupRole({data:{roomId,userId:p.userId,role:e.target.value as 'member'|'moderator'|'coadmin'}}))}><option value="member">Member</option><option value="moderator">Moderator</option><option value="coadmin">Co-admin</option></select></label>:null}{p.role==='member'&&group.role!=='member'||group.role==='owner'&&p.role!=='owner'?<Button size="sm" variant="secondary" disabled={busy} onClick={()=>{if(window.confirm(`Remove ${p.name} from this group?`))void act(()=>updateGroupChat({data:{roomId,removeUserId:p.userId}}));}}>Remove member</Button>:null}</div></div>)}</section>{admin&&group.invitations.length?<section className={card}><h2 className="font-bold">Pending invitations</h2>{group.invitations.map(i=><div key={i.id} className="flex flex-wrap items-center justify-between gap-2"><p>{i.name}</p><Button size="sm" disabled={busy} variant="secondary" onClick={()=>void act(()=>api.cancelGroupInvitation({data:{roomId,invitationId:i.id}}))}>Cancel invitation</Button></div>)}</section>:null}<Button variant="secondary" disabled={busy} onClick={()=>{if(window.confirm('Leave this group? Ownership passes to an administrator or remaining member.'))void act(async()=>{await updateGroupChat({data:{roomId,leave:true}});window.location.assign('/connections');});}}>Leave group</Button></div>;
}
export function EventParticipation({slug,eventId}:{slug:string;eventId:number}){
  const q=useQuery({queryKey:['eventParticipation',eventId],queryFn:()=>api.getEventParticipation({data:{slug,eventId}})}),[body,setBody]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await q.refetch();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  return <section className="space-y-3 rounded-xl bg-elevated p-3"><h4 className="font-bold">Event updates & attendance</h4>{q.isPending?<p>Loading…</p>:q.error?<p role="alert">{q.error.message}</p>:q.data?<>{error?<p role="alert" className="text-danger">{error}</p>:null}{q.data.mine?<p className="break-all text-sm">Attendance pass: <strong>{q.data.mine.code}</strong><br/>Status: {q.data.mine.state}</p>:null}{q.data.status!=='cancelled'?<><Button size="sm" disabled={busy} variant="secondary" onClick={()=>void act(()=>api.issueEventPass({data:{slug,eventId}}))}>{q.data.mine?'Refresh attendance pass':'Get attendance pass'}</Button><p className="text-xs text-muted">Requires a Going RSVP and any required ticket access. This pass records attendance; it does not charge you.</p><form className="space-y-2" onSubmit={e=>{e.preventDefault();void act(async()=>{await api.postEventTimeline({data:{slug,eventId,body}});setBody('');});}}><label className="block text-sm">Share an event update<textarea className={`${field} mt-1`} value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} required/></label><Button size="sm" disabled={busy}>Post update</Button></form></>:null}{q.data.timeline.map(t=><article key={t.id} className="space-y-1 rounded-xl bg-surface p-3"><a href={`/u/${t.handle}`} className="text-sm font-bold">{t.name}</a><p className="whitespace-pre-wrap text-sm">{t.body}</p><p className="text-xs text-muted">{new Date(t.createdAt).toLocaleString()}</p>{t.canDelete?<Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>api.deleteEventTimeline({data:{slug,eventId,postId:t.id}}))}>Remove update</Button>:null}</article>)}{q.data.organizer?<><form className="space-y-2" onSubmit={e=>{e.preventDefault();void act(()=>api.checkInEventPass({data:{slug,eventId,code,undo:false}}));}}><label className="block text-sm">Attendee pass code<input className={`${field} mt-1`} value={code} onChange={e=>setCode(e.target.value)} placeholder="Paste the attendee’s code" required/></label><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy||q.data.status==='cancelled'}>Check in</Button><Button size="sm" type="button" variant="secondary" disabled={busy||q.data.status==='cancelled'} onClick={()=>void act(()=>api.checkInEventPass({data:{slug,eventId,code,undo:true}}))}>Undo check-in</Button></div></form><p className="text-sm font-semibold">{q.data.passes.filter(p=>p.state==='checked_in').length} checked in · {q.data.passes.length} passes</p>{q.data.passes.map(p=><p key={p.id} className="text-sm">{p.name} · {p.state}</p>)}</>:null}</>:null}</section>;
}
