import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { actLiveStage,configureLiveStage,getLiveStage,reactLiveStage } from '@/lib/kamino/community-v9';
export function StageControls({roomId,userId}:{roomId:number;userId:string}){
  const q=useQuery({queryKey:['live-stage',roomId],queryFn:()=>getLiveStage({data:{roomId}}),refetchInterval:2500});const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await q.refetch();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  if(!q.data)return null;const data=q.data,me=data.participants.find(p=>p.userId===userId);
  return <details className="m-3 rounded-2xl bg-surface p-4 shadow-border" open={data.enabled}><summary className="cursor-pointer text-sm font-bold">{data.enabled?'Live stage':'Room controls'}{data.locked?' · Locked':''}</summary><div className="mt-3 space-y-3">{error?<p role="alert" className="text-sm text-danger">{error}</p>:null}{data.scheduledAt?<p className="text-xs text-muted">Scheduled {new Date(data.scheduledAt).toLocaleString()}</p>:null}<div className="flex flex-wrap gap-2">{data.host?<><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>configureLiveStage({data:{roomId,enabled:!data.enabled}}))}>{data.enabled?'Open conversation':'Enable stage'}</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>configureLiveStage({data:{roomId,locked:!data.locked}}))}>{data.locked?'Unlock room':'Lock room'}</Button></>:null}{data.enabled&&me?.role==='listener'?<Button size="sm" disabled={busy} onClick={()=>void act(()=>actLiveStage({data:{roomId,action:me.raised?'lower':'raise'}}))}>{me.raised?'Lower hand':'Raise hand'}</Button>:null}{['❤️','👏','🔥','🎉'].map(emoji=><button key={emoji} className="min-h-10 min-w-10 rounded-full bg-elevated text-lg" aria-label={`React ${emoji}`} disabled={busy} onClick={()=>void act(()=>reactLiveStage({data:{roomId,emoji:emoji as '❤️'|'👏'|'🔥'|'🎉'}}))}>{emoji}</button>)}</div><p className="text-xs text-muted">{data.reactions.map(r=>r.emoji).join(' ')}{me?.muted?' Your microphone is muted by the host.':data.enabled&&me?.role==='listener'?' You are listening. Raise your hand to speak.':''}</p>{data.participants.map(p=><div key={p.userId} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-elevated p-3"><div><p className="text-sm font-semibold">{p.nickname}{p.raised?' ✋':''}</p><p className="text-xs text-subtle">{p.cohost?'Co-host · ':''}{p.role}{p.muted?' · Muted':''}{p.inVoice?' · In room':''}</p></div>{data.host&&p.role!=='host'&&p.userId!==userId?<div className="flex flex-wrap gap-1"><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>actLiveStage({data:{roomId,userId:p.userId,action:p.cohost?'uncohost':'cohost'}}))}>{p.cohost?'Remove co-host':'Make co-host'}</Button>{(['speaker','listener','mute','unmute','remove'] as const).filter(a=>a==='remove'||a==='speaker'&&p.role==='listener'||a==='listener'&&p.role==='speaker'||a==='mute'&&!p.muted||a==='unmute'&&p.muted&&p.role==='speaker').map(action=><Button key={action} size="sm" variant="secondary" disabled={busy} onClick={()=>void act(()=>actLiveStage({data:{roomId,userId:p.userId,action}}))}>{action==='speaker'?'Invite to speak':action==='listener'?'Move to audience':action[0].toUpperCase()+action.slice(1)}</Button>)}</div>:null}</div>)}</div></details>;
}
